/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../app/app.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../app/auth/auth.service';
import * as import9 from '@angular/router/src/router';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import13 from '../node_modules/@angular/router/src/directives/router_outlet.ngfactory';
import * as import14 from '@angular/core/src/linker/template_ref';
import * as import15 from '@angular/router/src/router_outlet_map';
import * as import16 from '@angular/core/src/linker/component_factory_resolver';
import * as import17 from '@angular/common/src/directives/ng_if';
import * as import18 from '@angular/router/src/directives/router_outlet';
import * as import19 from '../node_modules/@angular/router/src/directives/router_link.ngfactory';
import * as import20 from '../node_modules/@angular/router/src/directives/router_link_active.ngfactory';
import * as import21 from '@angular/core/src/linker/query_list';
import * as import22 from '@angular/router/src/router_state';
import * as import23 from '@angular/common/src/location/location_strategy';
import * as import24 from '@angular/core/src/linker/element_ref';
import * as import25 from '@angular/router/src/directives/router_link';
import * as import26 from '@angular/router/src/directives/router_link_active';
export class Wrapper_AppComponent {
  context:import0.AppComponent;
  changed:boolean;
  constructor(p0:any,p1:any) {
    this.changed = false;
    this.context = new import0.AppComponent(p0,p1);
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_AppComponent_Host:import2.RenderComponentType = (null as any);
class _View_AppComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _AppComponent_0_4:Wrapper_AppComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AppComponent_Host0,renderType_AppComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'ddas-app',import4.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_AppComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._AppComponent_0_4 = new Wrapper_AppComponent(this.parentInjector.get(import8.AuthService),this.parentInjector.get(import9.Router));
    this._appEl_0.initComponent(this._AppComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._AppComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.AppComponent) && (0 === requestNodeIndex))) { return this._AppComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._AppComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._AppComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_AppComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_AppComponent_Host === (null as any))) { (renderType_AppComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_AppComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const AppComponentNgFactory:import11.ComponentFactory<import0.AppComponent> = new import11.ComponentFactory<import0.AppComponent>('ddas-app',viewFactory_AppComponent_Host0,import0.AppComponent);
const styles_AppComponent:any[] = ([] as any[]);
var renderType_AppComponent:import2.RenderComponentType = (null as any);
class _View_AppComponent0 extends import1.AppView<import0.AppComponent> {
  _text_0:any;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _TemplateRef_2_5:any;
  _NgIf_2_6:import12.Wrapper_NgIf;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import3.AppElement;
  _RouterOutlet_10_5:import13.Wrapper_RouterOutlet;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _anchor_14:any;
  /*private*/ _appEl_14:import3.AppElement;
  _TemplateRef_14_5:any;
  _NgIf_14_6:import12.Wrapper_NgIf;
  _text_15:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AppComponent0,renderType_AppComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._text_1 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_2 = new import3.AppElement(2,(null as any),this,this._anchor_2);
    this._TemplateRef_2_5 = new import14.TemplateRef_(this._appEl_2,viewFactory_AppComponent1);
    this._NgIf_2_6 = new import12.Wrapper_NgIf(this._appEl_2.vcRef,this._TemplateRef_2_5);
    this._text_3 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_4 = import4.createRenderElement(this.renderer,parentRenderNode,'br',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_5 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_6 = import4.createRenderElement(this.renderer,parentRenderNode,'div',new import4.InlineArray2(2,'class','container'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n    ',(null as any));
    this._el_8 = import4.createRenderElement(this.renderer,this._el_6,'div',new import4.InlineArray2(2,'class','row'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n \n    ',(null as any));
    this._el_10 = import4.createRenderElement(this.renderer,this._el_8,'router-outlet',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._appEl_10 = new import3.AppElement(10,8,this,this._el_10);
    this._RouterOutlet_10_5 = new import13.Wrapper_RouterOutlet(this.parentInjector.get(import15.RouterOutletMap),this._appEl_10.vcRef,this.parentInjector.get(import16.ComponentFactoryResolver),(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'    ',(null as any));
    this._text_12 = this.renderer.createText(this._el_8,'\n',(null as any));
    this._text_13 = this.renderer.createText(this._el_6,'\n',(null as any));
    this._anchor_14 = this.renderer.createTemplateAnchor(this._el_6,(null as any));
    this._appEl_14 = new import3.AppElement(14,6,this,this._anchor_14);
    this._TemplateRef_14_5 = new import14.TemplateRef_(this._appEl_14,viewFactory_AppComponent2);
    this._NgIf_14_6 = new import12.Wrapper_NgIf(this._appEl_14.vcRef,this._TemplateRef_14_5);
    this._text_15 = this.renderer.createText(this._el_6,'\n',(null as any));
    this.init(([] as any[]),[
      this._text_0,
      this._text_1,
      this._anchor_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._anchor_14,
      this._text_15
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import17.NgIf) && (2 === requestNodeIndex))) { return this._NgIf_2_6.context; }
    if (((token === import18.RouterOutlet) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._RouterOutlet_10_5.context; }
    if (((token === import14.TemplateRef) && (14 === requestNodeIndex))) { return this._TemplateRef_14_5; }
    if (((token === import17.NgIf) && (14 === requestNodeIndex))) { return this._NgIf_14_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2_0_0:any = this.context.authService.isLoggedIn;
    this._NgIf_2_6.check_ngIf(currVal_2_0_0,throwOnChange,false);
    this._NgIf_2_6.detectChangesInInputProps(this,this._anchor_2,throwOnChange);
    this._RouterOutlet_10_5.detectChangesInInputProps(this,this._el_10,throwOnChange);
    const currVal_14_0_0:any = this.context.authService.isLoggedIn;
    this._NgIf_14_6.check_ngIf(currVal_14_0_0,throwOnChange,false);
    this._NgIf_14_6.detectChangesInInputProps(this,this._anchor_14,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._RouterOutlet_10_5.detectChangesInHostProps(this,this._el_10,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterOutlet_10_5.context.ngOnDestroy();
  }
}
export function viewFactory_AppComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.AppComponent> {
  if ((renderType_AppComponent === (null as any))) { (renderType_AppComponent = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,styles_AppComponent,{})); }
  return new _View_AppComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_AppComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _RouterLinkWithHref_15_3:import19.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_15_4:import20.Wrapper_RouterLinkActive;
  _query_RouterLink_15_0:import21.QueryList<any>;
  _query_RouterLinkWithHref_15_1:import21.QueryList<any>;
  _text_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _RouterLinkWithHref_20_3:import19.Wrapper_RouterLinkWithHref;
  _RouterLinkActive_20_4:import20.Wrapper_RouterLinkActive;
  _query_RouterLink_20_0:import21.QueryList<any>;
  _query_RouterLinkWithHref_20_1:import21.QueryList<any>;
  _text_21:any;
  _text_22:any;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AppComponent1,renderType_AppComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.createRenderElement(this.renderer,(null as any),'nav',new import4.InlineArray4(4,'class','navbar navbar-inverse navbar-fixed-top ','role','navigation'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray2(2,'class','container'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import4.createRenderElement(this.renderer,this._el_2,'div',new import4.InlineArray2(2,'class','navbar-header'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = import4.createRenderElement(this.renderer,this._el_4,'img',new import4.InlineArray4(4,'class','img-responsive','src','assets\\images\\ICON-logo.gif'),(null as any));
    this._text_7 = this.renderer.createText(this._el_4,'\n\n        ',(null as any));
    this._text_8 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_9 = import4.createRenderElement(this.renderer,this._el_2,'div',new import4.InlineArray4(4,'class','collapse navbar-collapse','id','navbar-ex-collapse'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n            ',(null as any));
    this._el_11 = import4.createRenderElement(this.renderer,this._el_9,'ul',new import4.InlineArray2(2,'class','nav navbar-nav navbar-right'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'\n                 ',(null as any));
    this._el_13 = import4.createRenderElement(this.renderer,this._el_11,'li',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_14 = this.renderer.createText(this._el_13,' ',(null as any));
    this._el_15 = import4.createRenderElement(this.renderer,this._el_13,'a',new import4.InlineArray4(4,'routerLink','/search','routerLinkActive','active'),(null as any));
    this._RouterLinkWithHref_15_3 = new import19.Wrapper_RouterLinkWithHref(this.parentInjector.get(import9.Router),this.parentInjector.get(import22.ActivatedRoute),this.parentInjector.get(import23.LocationStrategy));
    this._RouterLinkActive_15_4 = new import20.Wrapper_RouterLinkActive(this.parentInjector.get(import9.Router),new import24.ElementRef(this._el_15),this.renderer);
    this._query_RouterLink_15_0 = new import21.QueryList<any>();
    this._query_RouterLinkWithHref_15_1 = new import21.QueryList<any>();
    this._text_16 = this.renderer.createText(this._el_15,'Search',(null as any));
    this._text_17 = this.renderer.createText(this._el_11,'\n                ',(null as any));
    this._el_18 = import4.createRenderElement(this.renderer,this._el_11,'li',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_19 = this.renderer.createText(this._el_18,' ',(null as any));
    this._el_20 = import4.createRenderElement(this.renderer,this._el_18,'a',new import4.InlineArray4(4,'routerLink','/logout','routerLinkActive','active'),(null as any));
    this._RouterLinkWithHref_20_3 = new import19.Wrapper_RouterLinkWithHref(this.parentInjector.get(import9.Router),this.parentInjector.get(import22.ActivatedRoute),this.parentInjector.get(import23.LocationStrategy));
    this._RouterLinkActive_20_4 = new import20.Wrapper_RouterLinkActive(this.parentInjector.get(import9.Router),new import24.ElementRef(this._el_20),this.renderer);
    this._query_RouterLink_20_0 = new import21.QueryList<any>();
    this._query_RouterLinkWithHref_20_1 = new import21.QueryList<any>();
    this._text_21 = this.renderer.createText(this._el_20,'Logout',(null as any));
    this._text_22 = this.renderer.createText(this._el_11,'\n                 \n                                       \n            ',(null as any));
    this._text_23 = this.renderer.createText(this._el_9,'\n        ',(null as any));
    this._text_24 = this.renderer.createText(this._el_2,'\n\n        ',(null as any));
    this._text_25 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_26 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._text_27 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_15,'click',this.eventHandler(this._handle_click_15_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_20,'click',this.eventHandler(this._handle_click_20_0.bind(this)));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._text_27
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import25.RouterLinkWithHref) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._RouterLinkWithHref_15_3.context; }
    if (((token === import26.RouterLinkActive) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 16)))) { return this._RouterLinkActive_15_4.context; }
    if (((token === import25.RouterLinkWithHref) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._RouterLinkWithHref_20_3.context; }
    if (((token === import26.RouterLinkActive) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 21)))) { return this._RouterLinkActive_20_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_15_0_0:any = '/search';
    this._RouterLinkWithHref_15_3.check_routerLink(currVal_15_0_0,throwOnChange,false);
    this._RouterLinkWithHref_15_3.detectChangesInInputProps(this,this._el_15,throwOnChange);
    const currVal_15_1_0:any = 'active';
    this._RouterLinkActive_15_4.check_routerLinkActive(currVal_15_1_0,throwOnChange,false);
    this._RouterLinkActive_15_4.detectChangesInInputProps(this,this._el_15,throwOnChange);
    const currVal_20_0_0:any = '/logout';
    this._RouterLinkWithHref_20_3.check_routerLink(currVal_20_0_0,throwOnChange,false);
    this._RouterLinkWithHref_20_3.detectChangesInInputProps(this,this._el_20,throwOnChange);
    const currVal_20_1_0:any = 'active';
    this._RouterLinkActive_20_4.check_routerLinkActive(currVal_20_1_0,throwOnChange,false);
    this._RouterLinkActive_20_4.detectChangesInInputProps(this,this._el_20,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_RouterLink_15_0.dirty) {
        this._query_RouterLink_15_0.reset(([] as any[]));
        this._RouterLinkActive_15_4.context.links = this._query_RouterLink_15_0;
        this._query_RouterLink_15_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_15_1.dirty) {
        this._query_RouterLinkWithHref_15_1.reset([this._RouterLinkWithHref_15_3.context]);
        this._RouterLinkActive_15_4.context.linksWithHrefs = this._query_RouterLinkWithHref_15_1;
        this._query_RouterLinkWithHref_15_1.notifyOnChanges();
      }
      if (this._query_RouterLink_20_0.dirty) {
        this._query_RouterLink_20_0.reset(([] as any[]));
        this._RouterLinkActive_20_4.context.links = this._query_RouterLink_20_0;
        this._query_RouterLink_20_0.notifyOnChanges();
      }
      if (this._query_RouterLinkWithHref_20_1.dirty) {
        this._query_RouterLinkWithHref_20_1.reset([this._RouterLinkWithHref_20_3.context]);
        this._RouterLinkActive_20_4.context.linksWithHrefs = this._query_RouterLinkWithHref_20_1;
        this._query_RouterLinkWithHref_20_1.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_15_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._RouterLinkActive_20_4.context.ngAfterContentInit(); }
    }
    this._RouterLinkWithHref_15_3.detectChangesInHostProps(this,this._el_15,throwOnChange);
    this._RouterLinkActive_15_4.detectChangesInHostProps(this,this._el_15,throwOnChange);
    this._RouterLinkWithHref_20_3.detectChangesInHostProps(this,this._el_20,throwOnChange);
    this._RouterLinkActive_20_4.detectChangesInHostProps(this,this._el_20,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._RouterLinkWithHref_15_3.context.ngOnDestroy();
    this._RouterLinkActive_15_4.context.ngOnDestroy();
    this._RouterLinkWithHref_20_3.context.ngOnDestroy();
    this._RouterLinkActive_20_4.context.ngOnDestroy();
  }
  private _handle_click_15_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_15_0:any = ((<any>this._RouterLinkWithHref_15_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_15_0);
  }
  private _handle_click_20_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_20_0:any = ((<any>this._RouterLinkWithHref_20_3.context.onClick($event.button,$event.ctrlKey,$event.metaKey)) !== false);
    return (true && pd_20_0);
  }
}
function viewFactory_AppComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_AppComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_AppComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _text_10:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_AppComponent2,renderType_AppComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.createRenderElement(this.renderer,(null as any),'footer',new import4.InlineArray2(2,'class','navbar navbar-inverse navbar-fixed-bottom'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray2(2,'class','text-center'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n        ',(null as any));
    this._el_4 = import4.createRenderElement(this.renderer,this._el_2,'h4',new import4.InlineArray2(2,'class','white'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n            ',(null as any));
    this._el_6 = import4.createRenderElement(this.renderer,this._el_4,'i',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'©2016 ICON plc - DDAS',(null as any));
    this._text_8 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._text_9 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n',(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._text_10
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
}
function viewFactory_AppComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_AppComponent2(viewUtils,parentInjector,declarationEl);
}