/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../../../app/shared/utils/ng2-uploader1/ng2-uploader';
import * as import2 from '@angular/core/src/di/injector';
class Ng2UploaderInjector extends import0.NgModuleInjector<import1.Ng2Uploader> {
  _Ng2Uploader_0:import1.Ng2Uploader;
  constructor(parent:import2.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.Ng2Uploader {
    this._Ng2Uploader_0 = new import1.Ng2Uploader();
    return this._Ng2Uploader_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.Ng2Uploader)) { return this._Ng2Uploader_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const Ng2UploaderNgFactory:import0.NgModuleFactory<import1.Ng2Uploader> = new import0.NgModuleFactory(Ng2UploaderInjector,import1.Ng2Uploader);