/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../../../../app/shared/utils/ng2-uploader/ng2-uploader';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
export class Wrapper_Ng2Uploader {
  context:import0.Ng2Uploader;
  changed:boolean;
  constructor() {
    this.changed = false;
    this.context = new import0.Ng2Uploader();
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_Ng2Uploader_Host:import2.RenderComponentType = (null as any);
class _View_Ng2Uploader_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _Ng2Uploader_0_4:Wrapper_Ng2Uploader;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_Ng2Uploader_Host0,renderType_Ng2Uploader_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'ng-component',import4.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_Ng2Uploader0(this.viewUtils,this.injector(0),this._appEl_0);
    this._Ng2Uploader_0_4 = new Wrapper_Ng2Uploader();
    this._appEl_0.initComponent(this._Ng2Uploader_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._Ng2Uploader_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.Ng2Uploader) && (0 === requestNodeIndex))) { return this._Ng2Uploader_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Ng2Uploader_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._Ng2Uploader_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_Ng2Uploader_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_Ng2Uploader_Host === (null as any))) { (renderType_Ng2Uploader_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_Ng2Uploader_Host0(viewUtils,parentInjector,declarationEl);
}
export const Ng2UploaderNgFactory:import9.ComponentFactory<import0.Ng2Uploader> = new import9.ComponentFactory<import0.Ng2Uploader>('ng-component',viewFactory_Ng2Uploader_Host0,import0.Ng2Uploader);
const styles_Ng2Uploader:any[] = ([] as any[]);
var renderType_Ng2Uploader:import2.RenderComponentType = (null as any);
class _View_Ng2Uploader0 extends import1.AppView<import0.Ng2Uploader> {
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_Ng2Uploader0,renderType_Ng2Uploader,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this.init(([] as any[]),([] as any[]),([] as any[]),([] as any[]));
    return (null as any);
  }
}
export function viewFactory_Ng2Uploader0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.Ng2Uploader> {
  if ((renderType_Ng2Uploader === (null as any))) { (renderType_Ng2Uploader = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,styles_Ng2Uploader,{})); }
  return new _View_Ng2Uploader0(viewUtils,parentInjector,declarationEl);
}