using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Utilities
{
    public class CountryList
    {
        public string Name { get; set; }
        public bool IsActive { get; set; }
        public List<CountryList> GetCountries {
            get {
                return new List<CountryList>
                {
                    new CountryList { Name = "Afghanistan", IsActive = false },
                    new CountryList { Name = "Albania", IsActive = false },
                    new CountryList { Name = "Algeria", IsActive = false },
                    new CountryList { Name = "American Samoa", IsActive = false },
                    new CountryList { Name = "Andorra", IsActive = false },
                    new CountryList { Name = "Angola", IsActive = false },
                    new CountryList { Name = "Anguilla", IsActive = false },
                    new CountryList { Name = "Antarctica", IsActive = false },
                    new CountryList { Name = "Antigua and Barbuda", IsActive = false },
                    new CountryList { Name = "Argentina", IsActive = false },
                    new CountryList { Name = "Armenia", IsActive = false },
                    new CountryList { Name = "Aruba", IsActive = false },
                    new CountryList { Name = "Australia", IsActive = true },
                    new CountryList { Name = "Austria", IsActive = false },
                    new CountryList { Name = "Azerbaijan", IsActive = false },
                    new CountryList { Name = "Bahamas", IsActive = false },
                    new CountryList { Name = "Bahrain", IsActive = false },
                    new CountryList { Name = "Bangladesh", IsActive = false },
                    new CountryList { Name = "Barbados", IsActive = false },
                    new CountryList { Name = "Belarus", IsActive = false },
                    new CountryList { Name = "Belgium", IsActive = true },
                    new CountryList { Name = "Belize", IsActive = false },
                    new CountryList { Name = "Benin", IsActive = false },
                    new CountryList { Name = "Bermuda", IsActive = false },
                    new CountryList { Name = "Bhutan", IsActive = false },
                    new CountryList { Name = "Bolivia", IsActive = false },
                    new CountryList { Name = "Bosnia and Herzegovina", IsActive = false },
                    new CountryList { Name = "Botswana", IsActive = false },
                    new CountryList { Name = "Bouvet Island", IsActive = false },
                    new CountryList { Name = "Brazil", IsActive = true },
                    new CountryList { Name = "British Antarctic Territory", IsActive = false },
                    new CountryList { Name = "British Indian Ocean Territory", IsActive = false },
                    new CountryList { Name = "British Virgin Islands", IsActive = false },
                    new CountryList { Name = "Brunei", IsActive = false },
                    new CountryList { Name = "Bulgaria", IsActive = false },
                    new CountryList { Name = "Burkina Faso", IsActive = false },
                    new CountryList { Name = "Burundi", IsActive = false },
                    new CountryList { Name = "Cambodia", IsActive = false },
                    new CountryList { Name = "Cameroon", IsActive = false },
                    new CountryList { Name = "Canada", IsActive = false },
                    new CountryList { Name = "Canton and Enderbury Islands", IsActive = false },
                    new CountryList { Name = "Cape Verde", IsActive = false },
                    new CountryList { Name = "Cayman Islands", IsActive = false },
                    new CountryList { Name = "Central African Republic", IsActive = false },
                    new CountryList { Name = "Chad", IsActive = false },
                    new CountryList { Name = "Chile", IsActive = false },
                    new CountryList { Name = "China", IsActive = false },
                    new CountryList { Name = "Christmas Island", IsActive = false },
                    new CountryList { Name = "Cocos [Keeling] Islands", IsActive = false },
                    new CountryList { Name = "Colombia", IsActive = true },
                    new CountryList { Name = "Comoros", IsActive = false },
                    new CountryList { Name = "Congo - Brazzaville", IsActive = false },
                    new CountryList { Name = "Congo - Kinshasa", IsActive = false },
                    new CountryList { Name = "Cook Islands", IsActive = false },
                    new CountryList { Name = "Costa Rica", IsActive = false },
                    new CountryList { Name = "Croatia", IsActive = false },
                    new CountryList { Name = "Cuba", IsActive = false },
                    new CountryList { Name = "Cyprus", IsActive = false },
                    new CountryList { Name = "Czech Republic", IsActive = false },
                    new CountryList { Name = "Côte d’Ivoire", IsActive = false },
                    new CountryList { Name = "Denmark", IsActive = false },
                    new CountryList { Name = "Djibouti", IsActive = false },
                    new CountryList { Name = "Dominica", IsActive = false },
                    new CountryList { Name = "Dominica", IsActive = false },
                    new CountryList { Name = "Dominican Republic", IsActive = false },
                    new CountryList { Name = "Dronning Maud Land", IsActive = false },
                    new CountryList { Name = "East Germany", IsActive = false },
                    new CountryList { Name = "Ecuador", IsActive = false },
                    new CountryList { Name = "Egypt", IsActive = false },
                    new CountryList { Name = "El Salvador", IsActive = false },
                    new CountryList { Name = "Equatorial Guinea", IsActive = false },
                    new CountryList { Name = "Eritrea", IsActive = false },
                    new CountryList { Name = "Estonia", IsActive = false },
                    new CountryList { Name = "Ethiopia", IsActive = false },
                    new CountryList { Name = "Falkland Islands", IsActive = false },
                    new CountryList { Name = "Faroe Islands", IsActive = false },
                    new CountryList { Name = "Fiji", IsActive = false },
                    new CountryList { Name = "Finland", IsActive = true },
                    new CountryList { Name = "France", IsActive = true },
                    new CountryList { Name = "French Guiana", IsActive = false },
                    new CountryList { Name = "French Polynesia", IsActive = false },
                    new CountryList { Name = "French Southern Territories", IsActive = false },
                    new CountryList { Name = "French Southern and Antarctic Territories", IsActive = false },
                    new CountryList { Name = "Gabon", IsActive = false },
                    new CountryList { Name = "Gambia", IsActive = false },
                    new CountryList { Name = "Georgia", IsActive = false },
                    new CountryList { Name = "Germany", IsActive = false },
                    new CountryList { Name = "Ghana", IsActive = false },
                    new CountryList { Name = "Gibraltar", IsActive = false },
                    new CountryList { Name = "Greece", IsActive = false },
                    new CountryList { Name = "Greenland", IsActive = false },
                    new CountryList { Name = "Grenada", IsActive = false },
                    new CountryList { Name = "Guadeloupe", IsActive = false },
                    new CountryList { Name = "Guam", IsActive = false },
                    new CountryList { Name = "Guatemala", IsActive = false },
                    new CountryList { Name = "Guernsey", IsActive = false },
                    new CountryList { Name = "Guinea", IsActive = false },
                    new CountryList { Name = "Guinea-Bissau", IsActive = false },
                    new CountryList { Name = "Guyana", IsActive = false },
                    new CountryList { Name = "Haiti", IsActive = false },
                    new CountryList { Name = "Heard Island and McDonald Islands", IsActive = false },
                    new CountryList { Name = "Honduras", IsActive = false },
                    new CountryList { Name = "Hong Kong SAR China", IsActive = false },
                    new CountryList { Name = "Hungary", IsActive = false },
                    new CountryList { Name = "Iceland", IsActive = false },
                    new CountryList { Name = "India", IsActive = true },
                    new CountryList { Name = "Indonesia", IsActive = false },
                    new CountryList { Name = "Iran", IsActive = false },
                    new CountryList { Name = "Iraq", IsActive = false },
                    new CountryList { Name = "Ireland", IsActive = false },
                    new CountryList { Name = "Isle of Man", IsActive = false },
                    new CountryList { Name = "Israel", IsActive = true },
                    new CountryList { Name = "Italy", IsActive = false },
                    new CountryList { Name = "Jamaica", IsActive = false },
                    new CountryList { Name = "Japan", IsActive = false },
                    new CountryList { Name = "Jersey", IsActive = false },
                    new CountryList { Name = "Johnston Island", IsActive = false },
                    new CountryList { Name = "Jordan", IsActive = false },
                    new CountryList { Name = "Kazakhstan", IsActive = false },
                    new CountryList { Name = "Kenya", IsActive = false },
                    new CountryList { Name = "Kiribati", IsActive = false },
                    new CountryList { Name = "Kuwait", IsActive = false },
                    new CountryList { Name = "Kyrgyzstan", IsActive = false },
                    new CountryList { Name = "Laos", IsActive = false },
                    new CountryList { Name = "Latvia", IsActive = false },
                    new CountryList { Name = "Lebanon", IsActive = false },
                    new CountryList { Name = "Lesotho", IsActive = false },
                    new CountryList { Name = "Liberia", IsActive = false },
                    new CountryList { Name = "Libya", IsActive = false },
                    new CountryList { Name = "Liechtenstein", IsActive = false },
                    new CountryList { Name = "Lithuania", IsActive = false },
                    new CountryList { Name = "Luxembourg", IsActive = false },
                    new CountryList { Name = "Macau SAR China", IsActive = false },
                    new CountryList { Name = "Macedonia", IsActive = false },
                    new CountryList { Name = "Madagascar", IsActive = false },
                    new CountryList { Name = "Malawi", IsActive = false },
                    new CountryList { Name = "Malaysia", IsActive = true },
                    new CountryList { Name = "Maldives", IsActive = false },
                    new CountryList { Name = "Mali", IsActive = false },
                    new CountryList { Name = "Malta", IsActive = false },
                    new CountryList { Name = "Marshall Islands", IsActive = false },
                    new CountryList { Name = "Martinique", IsActive = false },
                    new CountryList { Name = "Mauritania", IsActive = false },
                    new CountryList { Name = "Mauritius", IsActive = false },
                    new CountryList { Name = "Metropolitan France", IsActive = false },
                    new CountryList { Name = "Mexico", IsActive = false },
                    new CountryList { Name = "Micronesia", IsActive = false },
                    new CountryList { Name = "Midway Islands", IsActive = false },
                    new CountryList { Name = "Moldova", IsActive = false },
                    new CountryList { Name = "Monaco", IsActive = false },
                    new CountryList { Name = "Mongolia", IsActive = false },
                    new CountryList { Name = "Montenegro", IsActive = false },
                    new CountryList { Name = "Montserrat", IsActive = false },
                    new CountryList { Name = "Morocco", IsActive = false },
                    new CountryList { Name = "Mozambique", IsActive = false },
                    new CountryList { Name = "Myanmar [Burma]", IsActive = false },
                    new CountryList { Name = "Namibia", IsActive = false },
                    new CountryList { Name = "Nauru", IsActive = false },
                    new CountryList { Name = "Nepal", IsActive = false },
                    new CountryList { Name = "Netherlands", IsActive = false },
                    new CountryList { Name = "Netherlands Antilles", IsActive = false },
                    new CountryList { Name = "Neutral Zone", IsActive = false },
                    new CountryList { Name = "New Caledonia", IsActive = false },
                    new CountryList { Name = "New Zealand", IsActive = true },
                    new CountryList { Name = "Nicaragua", IsActive = false },
                    new CountryList { Name = "Niger", IsActive = false },
                    new CountryList { Name = "Nigeria", IsActive = false },
                    new CountryList { Name = "Niue", IsActive = false },
                    new CountryList { Name = "Norfolk Island", IsActive = false },
                    new CountryList { Name = "North Korea", IsActive = false },
                    new CountryList { Name = "North Vietnam", IsActive = false },
                    new CountryList { Name = "Northern Mariana Islands", IsActive = false },
                    new CountryList { Name = "Norway", IsActive = false },
                    new CountryList { Name = "Oman", IsActive = false },
                    new CountryList { Name = "Pacific Islands Trust Territory", IsActive = false },
                    new CountryList { Name = "Pakistan", IsActive = false },
                    new CountryList { Name = "Palau", IsActive = false },
                    new CountryList { Name = "Palestinian Territories", IsActive = false },
                    new CountryList { Name = "Panama", IsActive = false },
                    new CountryList { Name = "Panama Canal Zone", IsActive = false },
                    new CountryList { Name = "Papua New Guinea", IsActive = false },
                    new CountryList { Name = "Paraguay", IsActive = false },
                    new CountryList { Name = "People's Democratic Republic of Yemen", IsActive = false },
                    new CountryList { Name = "Peru", IsActive = true },
                    new CountryList { Name = "Philippines", IsActive = false },
                    new CountryList { Name = "Pitcairn Islands", IsActive = false },
                    new CountryList { Name = "Poland", IsActive = true },
                    new CountryList { Name = "Portugal", IsActive = true },
                    new CountryList { Name = "Puerto Rico", IsActive = false },
                    new CountryList { Name = "Qatar", IsActive = false },
                    new CountryList { Name = "Romania", IsActive = false },
                    new CountryList { Name = "Russia", IsActive = false },
                    new CountryList { Name = "Rwanda", IsActive = false },
                    new CountryList { Name = "Réunion", IsActive = false },
                    new CountryList { Name = "Saint Barthélemy", IsActive = false },
                    new CountryList { Name = "Saint Helena", IsActive = false },
                    new CountryList { Name = "Saint Kitts and Nevis", IsActive = false },
                    new CountryList { Name = "Saint Lucia", IsActive = false },
                    new CountryList { Name = "Saint Martin", IsActive = false },
                    new CountryList { Name = "Saint Pierre and Miquelon", IsActive = false },
                    new CountryList { Name = "Saint Vincent and the Grenadines", IsActive = false },
                    new CountryList { Name = "Samoa", IsActive = false },
                    new CountryList { Name = "San Marino", IsActive = false },
                    new CountryList { Name = "Saudi Arabia", IsActive = false },
                    new CountryList { Name = "Senegal", IsActive = false },
                    new CountryList { Name = "Serbia", IsActive = false },
                    new CountryList { Name = "Serbia and Montenegro", IsActive = false },
                    new CountryList { Name = "Seychelles", IsActive = false },
                    new CountryList { Name = "Sierra Leone", IsActive = false },
                    new CountryList { Name = "Singapore", IsActive = true },
                    new CountryList { Name = "Slovakia", IsActive = false },
                    new CountryList { Name = "Slovenia", IsActive = false },
                    new CountryList { Name = "Solomon Islands", IsActive = false },
                    new CountryList { Name = "Somalia", IsActive = false },
                    new CountryList { Name = "South Africa", IsActive = false },
                    new CountryList { Name = "South Georgia and the South Sandwich Islands", IsActive = false },
                    new CountryList { Name = "South Korea", IsActive = false },
                    new CountryList { Name = "Spain", IsActive = true },
                    new CountryList { Name = "Sri Lanka", IsActive = true },
                    new CountryList { Name = "Sudan", IsActive = false },
                    new CountryList { Name = "Suriname", IsActive = false },
                    new CountryList { Name = "Svalbard and Jan Mayen", IsActive = false },
                    new CountryList { Name = "Swaziland", IsActive = false },
                    new CountryList { Name = "Sweden", IsActive = false },
                    new CountryList { Name = "Switzerland", IsActive = false },
                    new CountryList { Name = "Syria", IsActive = false },
                    new CountryList { Name = "São Tomé and Príncipe", IsActive = false },
                    new CountryList { Name = "Taiwan", IsActive = false },
                    new CountryList { Name = "Tajikistan", IsActive = false },
                    new CountryList { Name = "Tanzania", IsActive = false },
                    new CountryList { Name = "Thailand", IsActive = false },
                    new CountryList { Name = "Timor-Leste", IsActive = false },
                    new CountryList { Name = "Togo", IsActive = false },
                    new CountryList { Name = "Tokelau", IsActive = false },
                    new CountryList { Name = "Tonga", IsActive = false },
                    new CountryList { Name = "Trinidad and Tobago", IsActive = false },
                    new CountryList { Name = "Tunisia", IsActive = false },
                    new CountryList { Name = "Turkey", IsActive = false },
                    new CountryList { Name = "Turkmenistan", IsActive = false },
                    new CountryList { Name = "Turks and Caicos Islands", IsActive = false },
                    new CountryList { Name = "Tuvalu", IsActive = false },
                    new CountryList { Name = "U.S. Minor Outlying Islands", IsActive = false },
                    new CountryList { Name = "U.S. Miscellaneous Pacific Islands", IsActive = false },
                    new CountryList { Name = "U.S. Virgin Islands", IsActive = false },
                    new CountryList { Name = "Uganda", IsActive = false },
                    new CountryList { Name = "Ukraine", IsActive = false },
                    new CountryList { Name = "Union of Soviet Socialist Republics", IsActive = false },
                    new CountryList { Name = "United Arab Emirates", IsActive = false },
                    new CountryList { Name = "United Kingdom", IsActive = false },
                    new CountryList { Name = "United States", IsActive = true },
                    new CountryList { Name = "Unknown or Invalid Region", IsActive = false },
                    new CountryList { Name = "Uruguay", IsActive = false },
                    new CountryList { Name = "Uzbekistan", IsActive = false },
                    new CountryList { Name = "Vanuatu", IsActive = false },
                    new CountryList { Name = "Vatican City", IsActive = false },
                    new CountryList { Name = "Venezuela", IsActive = false },
                    new CountryList { Name = "Vietnam", IsActive = false },
                    new CountryList { Name = "Wake Island", IsActive = false },
                    new CountryList { Name = "Wallis and Futuna", IsActive = false },
                    new CountryList { Name = "Western Sahara", IsActive = false },
                    new CountryList { Name = "Yemen", IsActive = false },
                    new CountryList { Name = "Zambia", IsActive = false },
                    new CountryList { Name = "Zimbabwe", IsActive = false },
                    new CountryList { Name = "Åland Islands", IsActive = false },
                };
            }
        }
    }
}
