/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../../app/search/search-detail.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../../app/search/search-service';
import * as import9 from '@angular/common/src/location/location';
import * as import10 from '@angular/router/src/router_state';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from './stylesTable.css.shim';
import * as import14 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import15 from '@angular/core/src/linker/template_ref';
import * as import16 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import17 from '@angular/common/src/directives/ng_for';
import * as import18 from '../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import19 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import20 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import21 from '../../node_modules/@angular/forms/src/directives/validators.ngfactory';
import * as import22 from '@angular/common/src/pipes/slice_pipe';
import * as import23 from '@angular/core/src/linker/element_ref';
import * as import24 from '@angular/forms/src/directives/default_value_accessor';
import * as import25 from '@angular/forms/src/directives/control_value_accessor';
import * as import26 from '@angular/forms/src/directives/ng_model';
import * as import27 from '@angular/forms/src/directives/ng_control';
import * as import28 from '@angular/forms/src/directives/ng_control_status';
import * as import29 from '@angular/forms/src/directives/validators';
import * as import30 from '@angular/forms/src/validators';
export class Wrapper_SearchDetailComponent {
  context:import0.SearchDetailComponent;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this.context = new import0.SearchDetailComponent(p0,p1,p2);
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_SearchDetailComponent_Host:import2.RenderComponentType = (null as any);
class _View_SearchDetailComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _SearchDetailComponent_0_4:Wrapper_SearchDetailComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_SearchDetailComponent_Host0,renderType_SearchDetailComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'search-detail',import4.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SearchDetailComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SearchDetailComponent_0_4 = new Wrapper_SearchDetailComponent(this.parentInjector.get(import8.SearchService),this.parentInjector.get(import9.Location),this.parentInjector.get(import10.ActivatedRoute));
    this._appEl_0.initComponent(this._SearchDetailComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._SearchDetailComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.SearchDetailComponent) && (0 === requestNodeIndex))) { return this._SearchDetailComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._SearchDetailComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._SearchDetailComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SearchDetailComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_SearchDetailComponent_Host === (null as any))) { (renderType_SearchDetailComponent_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_SearchDetailComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const SearchDetailComponentNgFactory:import12.ComponentFactory<import0.SearchDetailComponent> = new import12.ComponentFactory<import0.SearchDetailComponent>('search-detail',viewFactory_SearchDetailComponent_Host0,import0.SearchDetailComponent);
const styles_SearchDetailComponent:any[] = [import13.styles];
var renderType_SearchDetailComponent:import2.RenderComponentType = (null as any);
class _View_SearchDetailComponent0 extends import1.AppView<import0.SearchDetailComponent> {
  _text_0:any;
  _el_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _text_22:any;
  _el_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _el_32:any;
  _text_33:any;
  _el_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _el_38:any;
  _text_39:any;
  _el_40:any;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  _text_47:any;
  _text_48:any;
  _el_49:any;
  _text_50:any;
  _text_51:any;
  _el_52:any;
  _text_53:any;
  _text_54:any;
  _text_55:any;
  _text_56:any;
  _el_57:any;
  _text_58:any;
  _anchor_59:any;
  /*private*/ _appEl_59:import3.AppElement;
  _TemplateRef_59_5:any;
  _NgFor_59_6:import14.Wrapper_NgFor;
  _text_60:any;
  _text_61:any;
  _text_62:any;
  _text_63:any;
  _el_64:any;
  _text_65:any;
  _el_66:any;
  _text_67:any;
  _text_68:any;
  _el_69:any;
  _text_70:any;
  _text_71:any;
  _text_72:any;
  _text_73:any;
  _text_74:any;
  _text_75:any;
  /*private*/ _expr_79:any;
  /*private*/ _expr_80:any;
  /*private*/ _expr_81:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_SearchDetailComponent0,renderType_SearchDetailComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_79 = import7.UNINITIALIZED;
    this._expr_80 = import7.UNINITIALIZED;
    this._expr_81 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,' ',(null as any));
    this._el_1 = import4.createRenderElement(this.renderer,parentRenderNode,'div',new import4.InlineArray2(2,'class',''),(null as any));
    this._text_2 = this.renderer.createText(this._el_1,'',(null as any));
    this._el_3 = import4.createRenderElement(this.renderer,this._el_1,'div',new import4.InlineArray2(2,'class','panel panel-primary'),(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'\n        ',(null as any));
    this._el_5 = import4.createRenderElement(this.renderer,this._el_3,'div',new import4.InlineArray2(2,'class','panel-heading'),(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._el_7 = import4.createRenderElement(this.renderer,this._el_5,'div',new import4.InlineArray2(2,'class','container-fluid panel-container'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n                ',(null as any));
    this._el_9 = import4.createRenderElement(this.renderer,this._el_7,'div',new import4.InlineArray2(2,'class','row'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'\n                    ',(null as any));
    this._el_11 = import4.createRenderElement(this.renderer,this._el_9,'div',new import4.InlineArray2(2,'class','col-md-8 text-left'),(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'\n                        ',(null as any));
    this._el_13 = import4.createRenderElement(this.renderer,this._el_11,'h3',new import4.InlineArray2(2,'class','panel-title'),(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'\n                            ',(null as any));
    this._el_15 = import4.createRenderElement(this.renderer,this._el_13,'div',new import4.InlineArray4(4,'class','checkbox','style','display:inline'),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'\n                                ',(null as any));
    this._el_17 = import4.createRenderElement(this.renderer,this._el_15,'label',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'',(null as any));
    this._text_19 = this.renderer.createText(this._el_15,'\n                 \n                            ',(null as any));
    this._text_20 = this.renderer.createText(this._el_13,'\n                            \n                        ',(null as any));
    this._text_21 = this.renderer.createText(this._el_11,'\n                    ',(null as any));
    this._text_22 = this.renderer.createText(this._el_9,'\n                    ',(null as any));
    this._el_23 = import4.createRenderElement(this.renderer,this._el_9,'div',new import4.InlineArray2(2,'class','col-md-4 panel-title pull-right text-right'),(null as any));
    this._el_24 = import4.createRenderElement(this.renderer,this._el_23,'h3',new import4.InlineArray2(2,'class','panel-title'),(null as any));
    this._text_25 = this.renderer.createText(this._el_24,'',(null as any));
    this._text_26 = this.renderer.createText(this._el_9,'\n                    \n                ',(null as any));
    this._text_27 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._text_28 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._text_29 = this.renderer.createText(this._el_3,'\n        ',(null as any));
    this._el_30 = import4.createRenderElement(this.renderer,this._el_3,'div',new import4.InlineArray2(2,'class','panel-body'),(null as any));
    this._text_31 = this.renderer.createText(this._el_30,'\n \n             ',(null as any));
    this._el_32 = import4.createRenderElement(this.renderer,this._el_30,'div',new import4.InlineArray2(2,'class','table-responsive'),(null as any));
    this._text_33 = this.renderer.createText(this._el_32,'\n            ',(null as any));
    this._el_34 = import4.createRenderElement(this.renderer,this._el_32,'table',new import4.InlineArray2(2,'class','table table-bordered'),(null as any));
    this._text_35 = this.renderer.createText(this._el_34,'\n                ',(null as any));
    this._el_36 = import4.createRenderElement(this.renderer,this._el_34,'thead',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'\n                ',(null as any));
    this._el_38 = import4.createRenderElement(this.renderer,this._el_36,'tr',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_39 = this.renderer.createText(this._el_38,'\n                    \n                    ',(null as any));
    this._el_40 = import4.createRenderElement(this.renderer,this._el_38,'th',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_41 = this.renderer.createText(this._el_40,'Issue No',(null as any));
    this._text_42 = this.renderer.createText(this._el_38,'\n                     ',(null as any));
    this._el_43 = import4.createRenderElement(this.renderer,this._el_38,'th',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_44 = this.renderer.createText(this._el_43,'Status',(null as any));
    this._text_45 = this.renderer.createText(this._el_38,' \n                    ',(null as any));
    this._el_46 = import4.createRenderElement(this.renderer,this._el_38,'th',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_47 = this.renderer.createText(this._el_46,'Observations',(null as any));
    this._text_48 = this.renderer.createText(this._el_38,'\n                    ',(null as any));
    this._el_49 = import4.createRenderElement(this.renderer,this._el_38,'th',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_50 = this.renderer.createText(this._el_49,'Record Details',(null as any));
    this._text_51 = this.renderer.createText(this._el_38,'\n                    ',(null as any));
    this._el_52 = import4.createRenderElement(this.renderer,this._el_38,'th',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_53 = this.renderer.createText(this._el_52,'Record Location (Row Number)',(null as any));
    this._text_54 = this.renderer.createText(this._el_38,'\n   \n                ',(null as any));
    this._text_55 = this.renderer.createText(this._el_36,'\n                ',(null as any));
    this._text_56 = this.renderer.createText(this._el_34,'\n                ',(null as any));
    this._el_57 = import4.createRenderElement(this.renderer,this._el_34,'tbody',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_58 = this.renderer.createText(this._el_57,'\n                ',(null as any));
    this._anchor_59 = this.renderer.createTemplateAnchor(this._el_57,(null as any));
    this._appEl_59 = new import3.AppElement(59,57,this,this._anchor_59);
    this._TemplateRef_59_5 = new import15.TemplateRef_(this._appEl_59,viewFactory_SearchDetailComponent1);
    this._NgFor_59_6 = new import14.Wrapper_NgFor(this._appEl_59.vcRef,this._TemplateRef_59_5,this.parentInjector.get(import16.IterableDiffers),this.ref);
    this._text_60 = this.renderer.createText(this._el_57,'\n                \n                ',(null as any));
    this._text_61 = this.renderer.createText(this._el_34,'\n            ',(null as any));
    this._text_62 = this.renderer.createText(this._el_32,'\n          ',(null as any));
    this._text_63 = this.renderer.createText(this._el_30,'\n\n          ',(null as any));
    this._el_64 = import4.createRenderElement(this.renderer,this._el_30,'div',new import4.InlineArray2(2,'align','center'),(null as any));
    this._text_65 = this.renderer.createText(this._el_64,'\n             ',(null as any));
    this._el_66 = import4.createRenderElement(this.renderer,this._el_64,'button',new import4.InlineArray4(4,'class','btn btn-success','type','button'),(null as any));
    this._text_67 = this.renderer.createText(this._el_66,'Save',(null as any));
    this._text_68 = this.renderer.createText(this._el_64,'\n            ',(null as any));
    this._el_69 = import4.createRenderElement(this.renderer,this._el_64,'button',new import4.InlineArray4(4,'class','btn btn-default','type','button'),(null as any));
    this._text_70 = this.renderer.createText(this._el_69,'Back',(null as any));
    this._text_71 = this.renderer.createText(this._el_64,'\n          ',(null as any));
    this._text_72 = this.renderer.createText(this._el_30,'\n        ',(null as any));
    this._text_73 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._text_74 = this.renderer.createText(this._el_1,'\n  ',(null as any));
    this._text_75 = this.renderer.createText(parentRenderNode,'\n ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_66,'click',this.eventHandler(this._handle_click_66_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_69,'click',this.eventHandler(this._handle_click_69_0.bind(this)));
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._text_22,
      this._el_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._el_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._text_54,
      this._text_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._anchor_59,
      this._text_60,
      this._text_61,
      this._text_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._el_66,
      this._text_67,
      this._text_68,
      this._el_69,
      this._text_70,
      this._text_71,
      this._text_72,
      this._text_73,
      this._text_74,
      this._text_75
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.TemplateRef) && (59 === requestNodeIndex))) { return this._TemplateRef_59_5; }
    if (((token === import17.NgFor) && (59 === requestNodeIndex))) { return this._NgFor_59_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_59_0_0:any = this.context.matchedRecords;
    this._NgFor_59_6.check_ngForOf(currVal_59_0_0,throwOnChange,false);
    this._NgFor_59_6.detectChangesInInputProps(this,this._anchor_59,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_79:any = import4.interpolate(1,'\n    ',this.context.diagnostic,'\n    \n    ');
    if (import4.checkBinding(throwOnChange,this._expr_79,currVal_79)) {
      this.renderer.setText(this._text_2,currVal_79);
      this._expr_79 = currVal_79;
    }
    const currVal_80:any = import4.interpolate(2,'\n                                    ',this.context._SiteData.SiteName,' :',this.context._SiteData.NameToSearch,'\n                                       ');
    if (import4.checkBinding(throwOnChange,this._expr_80,currVal_80)) {
      this.renderer.setText(this._text_18,currVal_80);
      this._expr_80 = currVal_80;
    }
    const currVal_81:any = import4.interpolate(1,'Last saved at: ',this.context._SiteData.CreatedOn,' ');
    if (import4.checkBinding(throwOnChange,this._expr_81,currVal_81)) {
      this.renderer.setText(this._text_25,currVal_81);
      this._expr_81 = currVal_81;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_66_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_66_0:any = ((<any>this.context.saveSiteDetails()) !== false);
    return (true && pd_66_0);
  }
  private _handle_click_69_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_69_0:any = ((<any>this.context.goBack()) !== false);
    return (true && pd_69_0);
  }
}
export function viewFactory_SearchDetailComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.SearchDetailComponent> {
  if ((renderType_SearchDetailComponent === (null as any))) { (renderType_SearchDetailComponent = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.Emulated,styles_SearchDetailComponent,{})); }
  return new _View_SearchDetailComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_SearchDetailComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _DefaultValueAccessor_4_3:import18.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_4_4:any[];
  _NgModel_4_5:import19.Wrapper_NgModel;
  _NgControl_4_6:any;
  _NgControlStatus_4_7:import20.Wrapper_NgControlStatus;
  _text_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _DefaultValueAccessor_9_3:import18.Wrapper_DefaultValueAccessor;
  _NG_VALUE_ACCESSOR_9_4:any[];
  _NgModel_9_5:import19.Wrapper_NgModel;
  _NgControl_9_6:any;
  _NgControlStatus_9_7:import20.Wrapper_NgControlStatus;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _el_14:any;
  _DefaultValueAccessor_14_3:import18.Wrapper_DefaultValueAccessor;
  _RequiredValidator_14_4:import21.Wrapper_RequiredValidator;
  _NG_VALIDATORS_14_5:any[];
  _NG_VALUE_ACCESSOR_14_6:any[];
  _NgModel_14_7:import19.Wrapper_NgModel;
  _NgControl_14_8:any;
  _NgControlStatus_14_9:import20.Wrapper_NgControlStatus;
  _text_15:any;
  _text_16:any;
  _el_17:any;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _text_22:any;
  /*private*/ _expr_40:any;
  _pipe_slice_0:import22.SlicePipe;
  /*private*/ _expr_42:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_SearchDetailComponent1,renderType_SearchDetailComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_40 = import7.UNINITIALIZED;
    this._expr_42 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.createRenderElement(this.renderer,(null as any),'tr',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n                    \n                      ',(null as any));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'td',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n                          \n                         \n                          ',(null as any));
    this._el_4 = import4.createRenderElement(this.renderer,this._el_2,'input',new import4.InlineArray4(4,'placeholder','Status','type','text'),(null as any));
    this._DefaultValueAccessor_4_3 = new import18.Wrapper_DefaultValueAccessor(this.renderer,new import23.ElementRef(this._el_4));
    this._NG_VALUE_ACCESSOR_4_4 = [this._DefaultValueAccessor_4_3.context];
    this._NgModel_4_5 = new import19.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_4_4);
    this._NgControl_4_6 = this._NgModel_4_5.context;
    this._NgControlStatus_4_7 = new import20.Wrapper_NgControlStatus(this._NgControl_4_6);
    this._text_5 = this.renderer.createText(this._el_2,'\n                          ',(null as any));
    this._text_6 = this.renderer.createText(this._el_0,' \n                     ',(null as any));
    this._el_7 = import4.createRenderElement(this.renderer,this._el_0,'td',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n\n                         ',(null as any));
    this._el_9 = import4.createRenderElement(this.renderer,this._el_7,'input',new import4.InlineArray4(4,'placeholder','Status','type','text'),(null as any));
    this._DefaultValueAccessor_9_3 = new import18.Wrapper_DefaultValueAccessor(this.renderer,new import23.ElementRef(this._el_9));
    this._NG_VALUE_ACCESSOR_9_4 = [this._DefaultValueAccessor_9_3.context];
    this._NgModel_9_5 = new import19.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_9_4);
    this._NgControl_9_6 = this._NgModel_9_5.context;
    this._NgControlStatus_9_7 = new import20.Wrapper_NgControlStatus(this._NgControl_9_6);
    this._text_10 = this.renderer.createText(this._el_7,'\n\n                     ',(null as any));
    this._text_11 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._el_12 = import4.createRenderElement(this.renderer,this._el_0,'td',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_13 = this.renderer.createText(this._el_12,'\n                            ',(null as any));
    this._el_14 = import4.createRenderElement(this.renderer,this._el_12,'textarea',new import4.InlineArray8(8,'cols','30','placeholder','Observations','required','','rows','3'),(null as any));
    this._DefaultValueAccessor_14_3 = new import18.Wrapper_DefaultValueAccessor(this.renderer,new import23.ElementRef(this._el_14));
    this._RequiredValidator_14_4 = new import21.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_14_5 = [this._RequiredValidator_14_4.context];
    this._NG_VALUE_ACCESSOR_14_6 = [this._DefaultValueAccessor_14_3.context];
    this._NgModel_14_7 = new import19.Wrapper_NgModel((null as any),this._NG_VALIDATORS_14_5,(null as any),this._NG_VALUE_ACCESSOR_14_6);
    this._NgControl_14_8 = this._NgModel_14_7.context;
    this._NgControlStatus_14_9 = new import20.Wrapper_NgControlStatus(this._NgControl_14_8);
    this._text_15 = this.renderer.createText(this._el_12,'\n\n                    ',(null as any));
    this._text_16 = this.renderer.createText(this._el_0,'\n\n                    ',(null as any));
    this._el_17 = import4.createRenderElement(this.renderer,this._el_0,'td',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_18 = this.renderer.createText(this._el_17,'',(null as any));
    this._text_19 = this.renderer.createText(this._el_0,'\n                    ',(null as any));
    this._el_20 = import4.createRenderElement(this.renderer,this._el_0,'td',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'',(null as any));
    this._text_22 = this.renderer.createText(this._el_0,'\n                \n                 ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_4,'ngModelChange',this.eventHandler(this._handle_ngModelChange_4_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_4,'input',this.eventHandler(this._handle_input_4_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_4,'blur',this.eventHandler(this._handle_blur_4_2.bind(this)));
    const subscription_0:any = this._NgModel_4_5.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_4_0.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_9,'ngModelChange',this.eventHandler(this._handle_ngModelChange_9_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_9,'input',this.eventHandler(this._handle_input_9_1.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_9,'blur',this.eventHandler(this._handle_blur_9_2.bind(this)));
    const subscription_1:any = this._NgModel_9_5.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_9_0.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_14,'ngModelChange',this.eventHandler(this._handle_ngModelChange_14_0.bind(this)));
    var disposable_7:Function = this.renderer.listen(this._el_14,'input',this.eventHandler(this._handle_input_14_1.bind(this)));
    var disposable_8:Function = this.renderer.listen(this._el_14,'blur',this.eventHandler(this._handle_blur_14_2.bind(this)));
    const subscription_2:any = this._NgModel_14_7.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_14_0.bind(this)));
    this._pipe_slice_0 = new import22.SlicePipe();
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._text_22
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.DefaultValueAccessor) && (4 === requestNodeIndex))) { return this._DefaultValueAccessor_4_3.context; }
    if (((token === import25.NG_VALUE_ACCESSOR) && (4 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_4_4; }
    if (((token === import26.NgModel) && (4 === requestNodeIndex))) { return this._NgModel_4_5.context; }
    if (((token === import27.NgControl) && (4 === requestNodeIndex))) { return this._NgControl_4_6; }
    if (((token === import28.NgControlStatus) && (4 === requestNodeIndex))) { return this._NgControlStatus_4_7.context; }
    if (((token === import24.DefaultValueAccessor) && (9 === requestNodeIndex))) { return this._DefaultValueAccessor_9_3.context; }
    if (((token === import25.NG_VALUE_ACCESSOR) && (9 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_9_4; }
    if (((token === import26.NgModel) && (9 === requestNodeIndex))) { return this._NgModel_9_5.context; }
    if (((token === import27.NgControl) && (9 === requestNodeIndex))) { return this._NgControl_9_6; }
    if (((token === import28.NgControlStatus) && (9 === requestNodeIndex))) { return this._NgControlStatus_9_7.context; }
    if (((token === import24.DefaultValueAccessor) && (14 === requestNodeIndex))) { return this._DefaultValueAccessor_14_3.context; }
    if (((token === import29.RequiredValidator) && (14 === requestNodeIndex))) { return this._RequiredValidator_14_4.context; }
    if (((token === import30.NG_VALIDATORS) && (14 === requestNodeIndex))) { return this._NG_VALIDATORS_14_5; }
    if (((token === import25.NG_VALUE_ACCESSOR) && (14 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_14_6; }
    if (((token === import26.NgModel) && (14 === requestNodeIndex))) { return this._NgModel_14_7.context; }
    if (((token === import27.NgControl) && (14 === requestNodeIndex))) { return this._NgControl_14_8; }
    if (((token === import28.NgControlStatus) && (14 === requestNodeIndex))) { return this._NgControlStatus_14_9.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    this._DefaultValueAccessor_4_3.detectChangesInInputProps(this,this._el_4,throwOnChange);
    const currVal_4_1_0:any = this.context.$implicit.IssueNumber;
    this._NgModel_4_5.check_model(currVal_4_1_0,throwOnChange,false);
    this._NgModel_4_5.detectChangesInInputProps(this,this._el_4,throwOnChange);
    this._NgControlStatus_4_7.detectChangesInInputProps(this,this._el_4,throwOnChange);
    this._DefaultValueAccessor_9_3.detectChangesInInputProps(this,this._el_9,throwOnChange);
    const currVal_9_1_0:any = this.context.$implicit.Status;
    this._NgModel_9_5.check_model(currVal_9_1_0,throwOnChange,false);
    this._NgModel_9_5.detectChangesInInputProps(this,this._el_9,throwOnChange);
    this._NgControlStatus_9_7.detectChangesInInputProps(this,this._el_9,throwOnChange);
    this._DefaultValueAccessor_14_3.detectChangesInInputProps(this,this._el_14,throwOnChange);
    const currVal_14_1_0:any = '';
    this._RequiredValidator_14_4.check_required(currVal_14_1_0,throwOnChange,false);
    this._RequiredValidator_14_4.detectChangesInInputProps(this,this._el_14,throwOnChange);
    const currVal_14_2_0:any = this.context.$implicit.Issues;
    this._NgModel_14_7.check_model(currVal_14_2_0,throwOnChange,false);
    this._NgModel_14_7.detectChangesInInputProps(this,this._el_14,throwOnChange);
    this._NgControlStatus_14_9.detectChangesInInputProps(this,this._el_14,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._DefaultValueAccessor_4_3.detectChangesInHostProps(this,this._el_4,throwOnChange);
    this._NgModel_4_5.detectChangesInHostProps(this,this._el_4,throwOnChange);
    this._NgControlStatus_4_7.detectChangesInHostProps(this,this._el_4,throwOnChange);
    this._DefaultValueAccessor_9_3.detectChangesInHostProps(this,this._el_9,throwOnChange);
    this._NgModel_9_5.detectChangesInHostProps(this,this._el_9,throwOnChange);
    this._NgControlStatus_9_7.detectChangesInHostProps(this,this._el_9,throwOnChange);
    this._DefaultValueAccessor_14_3.detectChangesInHostProps(this,this._el_14,throwOnChange);
    this._RequiredValidator_14_4.detectChangesInHostProps(this,this._el_14,throwOnChange);
    this._NgModel_14_7.detectChangesInHostProps(this,this._el_14,throwOnChange);
    this._NgControlStatus_14_9.detectChangesInHostProps(this,this._el_14,throwOnChange);
    valUnwrapper.reset();
    const currVal_40:any = import4.interpolate(1,'',valUnwrapper.unwrap(this._pipe_slice_0.transform(this.context.$implicit.RecordDetails,0,150)),' ...');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_40,currVal_40))) {
      this.renderer.setText(this._text_18,currVal_40);
      this._expr_40 = currVal_40;
    }
    const currVal_42:any = import4.interpolate(1,'',this.context.$implicit.RowNumber,'');
    if (import4.checkBinding(throwOnChange,this._expr_42,currVal_42)) {
      this.renderer.setText(this._text_21,currVal_42);
      this._expr_42 = currVal_42;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_4_5.context.ngOnDestroy();
    this._NgModel_9_5.context.ngOnDestroy();
    this._NgModel_14_7.context.ngOnDestroy();
  }
  private _handle_ngModelChange_4_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_4_0:any = ((<any>(this.context.$implicit.IssueNumber = $event)) !== false);
    return (true && pd_4_0);
  }
  private _handle_input_4_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_4_0:any = ((<any>this._DefaultValueAccessor_4_3.context.onChange($event.target.value)) !== false);
    return (true && pd_4_0);
  }
  private _handle_blur_4_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_4_0:any = ((<any>this._DefaultValueAccessor_4_3.context.onTouched()) !== false);
    return (true && pd_4_0);
  }
  private _handle_ngModelChange_9_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_9_0:any = ((<any>(this.context.$implicit.Status = $event)) !== false);
    return (true && pd_9_0);
  }
  private _handle_input_9_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_9_0:any = ((<any>this._DefaultValueAccessor_9_3.context.onChange($event.target.value)) !== false);
    return (true && pd_9_0);
  }
  private _handle_blur_9_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_9_0:any = ((<any>this._DefaultValueAccessor_9_3.context.onTouched()) !== false);
    return (true && pd_9_0);
  }
  private _handle_ngModelChange_14_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_14_0:any = ((<any>(this.context.$implicit.Issues = $event)) !== false);
    return (true && pd_14_0);
  }
  private _handle_input_14_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_14_0:any = ((<any>this._DefaultValueAccessor_14_3.context.onChange($event.target.value)) !== false);
    return (true && pd_14_0);
  }
  private _handle_blur_14_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_14_0:any = ((<any>this._DefaultValueAccessor_14_3.context.onTouched()) !== false);
    return (true && pd_14_0);
  }
}
function viewFactory_SearchDetailComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_SearchDetailComponent1(viewUtils,parentInjector,declarationEl);
}