/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../app/search/search.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/forms/src/directives';
import * as import4 from '@angular/forms/src/form_providers';
import * as import5 from '@angular/router/src/router_module';
import * as import6 from '../../../app/shared/utils/ng2-uploader1/ng2-uploader';
import * as import7 from '@angular/common/src/localization';
import * as import8 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import9 from '@angular/core/src/di/injector';
import * as import10 from './search.component.ngfactory';
import * as import11 from './search-input.component.ngfactory';
import * as import12 from './search-detail.component.ngfactory';
import * as import13 from './search-result-summary.component.ngfactory';
import * as import14 from '@angular/core/src/i18n/tokens';
import * as import15 from '../../../app/search/search.component';
import * as import16 from '../../../app/auth/auth-guard.service';
import * as import17 from '../../../app/search/search-input.component';
import * as import18 from '../../../app/search/search-detail.component';
import * as import19 from '../../../app/search/search-result-summary.component';
import * as import20 from '@angular/router/src/router_config_loader';
class SearchModuleInjector extends import0.NgModuleInjector<import1.SearchModule> {
  _CommonModule_0:import2.CommonModule;
  _InternalFormsSharedModule_1:import3.InternalFormsSharedModule;
  _FormsModule_2:import4.FormsModule;
  _RouterModule_3:import5.RouterModule;
  _Ng2Uploader_4:import6.Ng2Uploader;
  _SearchModule_5:import1.SearchModule;
  __NgLocalization_6:import7.NgLocaleLocalization;
  __RadioControlRegistry_7:import8.RadioControlRegistry;
  __ROUTES_8:any[];
  constructor(parent:import9.Injector) {
    super(parent,[
      import10.SearchComponentNgFactory,
      import11.SearchInputComponentNgFactory,
      import12.SearchDetailComponentNgFactory,
      import13.SearchResultSummaryComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _NgLocalization_6():import7.NgLocaleLocalization {
    if ((this.__NgLocalization_6 == (null as any))) { (this.__NgLocalization_6 = new import7.NgLocaleLocalization(this.parent.get(import14.LOCALE_ID))); }
    return this.__NgLocalization_6;
  }
  get _RadioControlRegistry_7():import8.RadioControlRegistry {
    if ((this.__RadioControlRegistry_7 == (null as any))) { (this.__RadioControlRegistry_7 = new import8.RadioControlRegistry()); }
    return this.__RadioControlRegistry_7;
  }
  get _ROUTES_8():any[] {
      if ((this.__ROUTES_8 == (null as any))) { (this.__ROUTES_8 = [[
        {
          path: '',
          redirectTo: '/search',
          pathMatch: 'full'
        }
        ,
        {
          path: 'search',
          component: import15.SearchComponent,
          canActivate: [import16.AuthGuard],
          children: [
            {
              path: '',
              component: import17.SearchInputComponent
            }
            ,
            {
              path: 'details/:siteEnum/:name/:id',
              component: import18.SearchDetailComponent
            }
            ,
            {
              path: 'summary/:name',
              component: import19.SearchResultSummaryComponent
            }

          ]

        }

      ]
    ]); }
    return this.__ROUTES_8;
  }
  createInternal():import1.SearchModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._InternalFormsSharedModule_1 = new import3.InternalFormsSharedModule();
    this._FormsModule_2 = new import4.FormsModule();
    this._RouterModule_3 = new import5.RouterModule(this.parent.get(import5.ROUTER_FORROOT_GUARD,(null as any)));
    this._Ng2Uploader_4 = new import6.Ng2Uploader();
    this._SearchModule_5 = new import1.SearchModule();
    return this._SearchModule_5;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_1; }
    if ((token === import4.FormsModule)) { return this._FormsModule_2; }
    if ((token === import5.RouterModule)) { return this._RouterModule_3; }
    if ((token === import6.Ng2Uploader)) { return this._Ng2Uploader_4; }
    if ((token === import1.SearchModule)) { return this._SearchModule_5; }
    if ((token === import7.NgLocalization)) { return this._NgLocalization_6; }
    if ((token === import8.RadioControlRegistry)) { return this._RadioControlRegistry_7; }
    if ((token === import20.ROUTES)) { return this._ROUTES_8; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const SearchModuleNgFactory:import0.NgModuleFactory<import1.SearchModule> = new import0.NgModuleFactory(SearchModuleInjector,import1.SearchModule);