/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../../app/search/search-input.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/router/src/router_state';
import * as import9 from '@angular/router/src/router';
import * as import10 from '../../../app/shared/utils/config.service';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from '../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import14 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import15 from '../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import16 from '../../node_modules/@angular/forms/src/directives/validators.ngfactory';
import * as import17 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import18 from '../shared/utils/ng2-uploader1/src/directives/ng-file-select.ngfactory';
import * as import19 from '../../node_modules/@angular/common/src/directives/ng_for.ngfactory';
import * as import20 from '@angular/common/src/pipes/json_pipe';
import * as import21 from '@angular/core/src/linker/element_ref';
import * as import22 from '@angular/core/src/linker/template_ref';
import * as import23 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import24 from '@angular/forms/src/directives/default_value_accessor';
import * as import25 from '@angular/forms/src/directives/validators';
import * as import26 from '@angular/forms/src/validators';
import * as import27 from '@angular/forms/src/directives/control_value_accessor';
import * as import28 from '@angular/forms/src/directives/ng_model';
import * as import29 from '@angular/forms/src/directives/ng_control';
import * as import30 from '@angular/forms/src/directives/ng_control_status';
import * as import31 from '@angular/forms/src/directives/ng_form';
import * as import32 from '@angular/forms/src/directives/control_container';
import * as import33 from '../../../app/shared/utils/ng2-uploader1/src/directives/ng-file-select';
import * as import34 from '@angular/common/src/directives/ng_for';
import * as import35 from '@angular/core/src/security';
export class Wrapper_SearchInputComponent {
  context:import0.SearchInputComponent;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any) {
    this.changed = false;
    this.context = new import0.SearchInputComponent(p0,p1,p2);
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_SearchInputComponent_Host:import2.RenderComponentType = (null as any);
class _View_SearchInputComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _SearchInputComponent_0_4:Wrapper_SearchInputComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_SearchInputComponent_Host0,renderType_SearchInputComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'ng-component',import4.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SearchInputComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SearchInputComponent_0_4 = new Wrapper_SearchInputComponent(this.parentInjector.get(import8.ActivatedRoute),this.parentInjector.get(import9.Router),this.parentInjector.get(import10.ConfigService));
    this._appEl_0.initComponent(this._SearchInputComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._SearchInputComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.SearchInputComponent) && (0 === requestNodeIndex))) { return this._SearchInputComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._SearchInputComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._SearchInputComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SearchInputComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_SearchInputComponent_Host === (null as any))) { (renderType_SearchInputComponent_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_SearchInputComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const SearchInputComponentNgFactory:import12.ComponentFactory<import0.SearchInputComponent> = new import12.ComponentFactory<import0.SearchInputComponent>('ng-component',viewFactory_SearchInputComponent_Host0,import0.SearchInputComponent);
const styles_SearchInputComponent:any[] = ([] as any[]);
var renderType_SearchInputComponent:import2.RenderComponentType = (null as any);
class _View_SearchInputComponent0 extends import1.AppView<import0.SearchInputComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _el_4:any;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _text_16:any;
  _el_17:any;
  _NgForm_17_3:import13.Wrapper_NgForm;
  _ControlContainer_17_4:any;
  _NgControlStatusGroup_17_5:import14.Wrapper_NgControlStatusGroup;
  _text_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _DefaultValueAccessor_25_3:import15.Wrapper_DefaultValueAccessor;
  _RequiredValidator_25_4:import16.Wrapper_RequiredValidator;
  _NG_VALIDATORS_25_5:any[];
  _NG_VALUE_ACCESSOR_25_6:any[];
  _NgModel_25_7:import17.Wrapper_NgModel;
  _NgControl_25_8:any;
  _NgControlStatus_25_9:import14.Wrapper_NgControlStatus;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _el_35:any;
  _NgForm_35_3:import13.Wrapper_NgForm;
  _ControlContainer_35_4:any;
  _NgControlStatusGroup_35_5:import14.Wrapper_NgControlStatusGroup;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _text_47:any;
  _text_48:any;
  _el_49:any;
  _NgFileSelectDirective_49_3:import18.Wrapper_NgFileSelectDirective;
  _text_50:any;
  _el_51:any;
  _text_52:any;
  _text_53:any;
  _el_54:any;
  _text_55:any;
  _text_56:any;
  _text_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _el_61:any;
  _text_62:any;
  _el_63:any;
  _text_64:any;
  _el_65:any;
  _text_66:any;
  _text_67:any;
  _el_68:any;
  _text_69:any;
  _el_70:any;
  _text_71:any;
  _el_72:any;
  _text_73:any;
  _el_74:any;
  _text_75:any;
  _el_76:any;
  _text_77:any;
  _text_78:any;
  _el_79:any;
  _text_80:any;
  _text_81:any;
  _el_82:any;
  _text_83:any;
  _text_84:any;
  _el_85:any;
  _text_86:any;
  _text_87:any;
  _text_88:any;
  _text_89:any;
  _el_90:any;
  _text_91:any;
  _anchor_92:any;
  /*private*/ _appEl_92:import3.AppElement;
  _TemplateRef_92_5:any;
  _NgFor_92_6:import19.Wrapper_NgFor;
  _text_93:any;
  _text_94:any;
  _text_95:any;
  _text_96:any;
  _el_97:any;
  _text_98:any;
  _text_99:any;
  _text_100:any;
  _text_101:any;
  _text_102:any;
  _text_103:any;
  /*private*/ _expr_121:any;
  /*private*/ _expr_122:any;
  /*private*/ _expr_123:any;
  _pipe_json_0:import20.JsonPipe;
  /*private*/ _expr_125:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_SearchInputComponent0,renderType_SearchInputComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_121 = import7.UNINITIALIZED;
    this._expr_122 = import7.UNINITIALIZED;
    this._expr_123 = import7.UNINITIALIZED;
    this._expr_125 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = import4.createRenderElement(this.renderer,parentRenderNode,'div',new import4.InlineArray2(2,'class','section'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n	',(null as any));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'div',new import4.InlineArray2(2,'class','container'),(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'\n		',(null as any));
    this._el_4 = import4.createRenderElement(this.renderer,this._el_2,'div',new import4.InlineArray2(2,'class','row'),(null as any));
    this._text_5 = this.renderer.createText(this._el_4,'\n			',(null as any));
    this._el_6 = import4.createRenderElement(this.renderer,this._el_4,'div',new import4.InlineArray2(2,'class','col-md-12'),(null as any));
    this._text_7 = this.renderer.createText(this._el_6,'\n				',(null as any));
    this._el_8 = import4.createRenderElement(this.renderer,this._el_6,'div',new import4.InlineArray2(2,'class','well'),(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'\n\n					',(null as any));
    this._el_10 = import4.createRenderElement(this.renderer,this._el_8,'h3',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'Add names to search',(null as any));
    this._text_12 = this.renderer.createText(this._el_8,'\n\n					',(null as any));
    this._el_13 = import4.createRenderElement(this.renderer,this._el_8,'div',new import4.InlineArray2(2,'class','row'),(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'\n						',(null as any));
    this._el_15 = import4.createRenderElement(this.renderer,this._el_13,'div',new import4.InlineArray2(2,'class','col-md-6'),(null as any));
    this._text_16 = this.renderer.createText(this._el_15,'\n							',(null as any));
    this._el_17 = import4.createRenderElement(this.renderer,this._el_15,'form',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._NgForm_17_3 = new import13.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_17_4 = this._NgForm_17_3.context;
    this._NgControlStatusGroup_17_5 = new import14.Wrapper_NgControlStatusGroup(this._ControlContainer_17_4);
    this._text_18 = this.renderer.createText(this._el_17,'\n								',(null as any));
    this._text_19 = this.renderer.createText(this._el_17,'\n								',(null as any));
    this._el_20 = import4.createRenderElement(this.renderer,this._el_17,'div',new import4.InlineArray2(2,'class','form-group'),(null as any));
    this._text_21 = this.renderer.createText(this._el_20,'\n\n									',(null as any));
    this._el_22 = import4.createRenderElement(this.renderer,this._el_20,'label',new import4.InlineArray4(4,'class','control-label','for','exampleInputEmail1'),(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'Add a name to search:',(null as any));
    this._text_24 = this.renderer.createText(this._el_20,'\n									',(null as any));
    this._el_25 = import4.createRenderElement(this.renderer,this._el_20,'textarea',new import4.InlineArray16(16,'class','form-control','cols','30','id','TextArea1','name','NameToSearch','ngcontroll','NameToSearch','placeholder','Enter a name to search, example:Ramesh Krishnan Venkat Narayan, first name, middle name, last name order is not important. ','required','','rows','3'),(null as any));
    this._DefaultValueAccessor_25_3 = new import15.Wrapper_DefaultValueAccessor(this.renderer,new import21.ElementRef(this._el_25));
    this._RequiredValidator_25_4 = new import16.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_25_5 = [this._RequiredValidator_25_4.context];
    this._NG_VALUE_ACCESSOR_25_6 = [this._DefaultValueAccessor_25_3.context];
    this._NgModel_25_7 = new import17.Wrapper_NgModel(this._ControlContainer_17_4,this._NG_VALIDATORS_25_5,(null as any),this._NG_VALUE_ACCESSOR_25_6);
    this._NgControl_25_8 = this._NgModel_25_7.context;
    this._NgControlStatus_25_9 = new import14.Wrapper_NgControlStatus(this._NgControl_25_8);
    this._text_26 = this.renderer.createText(this._el_20,'\n								',(null as any));
    this._text_27 = this.renderer.createText(this._el_17,'\n								',(null as any));
    this._el_28 = import4.createRenderElement(this.renderer,this._el_17,'button',new import4.InlineArray4(4,'class','btn btn-primary','type','button'),(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'Add',(null as any));
    this._text_30 = this.renderer.createText(this._el_17,'\n							',(null as any));
    this._text_31 = this.renderer.createText(this._el_15,'\n						',(null as any));
    this._text_32 = this.renderer.createText(this._el_13,'\n						',(null as any));
    this._el_33 = import4.createRenderElement(this.renderer,this._el_13,'div',new import4.InlineArray2(2,'class','col-md-6'),(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'\n							',(null as any));
    this._el_35 = import4.createRenderElement(this.renderer,this._el_33,'form',new import4.InlineArray4(4,'enctype','multipart/form-data','method','post'),(null as any));
    this._NgForm_35_3 = new import13.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_35_4 = this._NgForm_35_3.context;
    this._NgControlStatusGroup_35_5 = new import14.Wrapper_NgControlStatusGroup(this._ControlContainer_35_4);
    this._text_36 = this.renderer.createText(this._el_35,'\n								',(null as any));
    this._el_37 = import4.createRenderElement(this.renderer,this._el_35,'div',new import4.InlineArray2(2,'class','form-group'),(null as any));
    this._text_38 = this.renderer.createText(this._el_37,'\n\n									',(null as any));
    this._el_39 = import4.createRenderElement(this.renderer,this._el_37,'label',new import4.InlineArray4(4,'class','control-label','for','fileupload'),(null as any));
    this._text_40 = this.renderer.createText(this._el_39,' Select a file to upload - (.csv file with list of names to search):',(null as any));
    this._text_41 = this.renderer.createText(this._el_37,'\n									',(null as any));
    this._el_42 = import4.createRenderElement(this.renderer,this._el_37,'input',new import4.InlineArray16(10,'class','form-control','id','fileupload','name','fileupload','type','file','value','fileupload'),(null as any));
    this._text_43 = this.renderer.createText(this._el_37,'\n\n								',(null as any));
    this._text_44 = this.renderer.createText(this._el_35,'\n								',(null as any));
    this._el_45 = import4.createRenderElement(this.renderer,this._el_35,'input',new import4.InlineArray8(6,'class','btn btn-primary','type','submit','value','Add a '),(null as any));
    this._text_46 = this.renderer.createText(this._el_35,'\n							',(null as any));
    this._text_47 = this.renderer.createText(this._el_33,'\n							',(null as any));
    this._text_48 = this.renderer.createText(this._el_33,'\n							',(null as any));
    this._el_49 = import4.createRenderElement(this.renderer,this._el_33,'input',new import4.InlineArray4(4,'ngFileSelect','','type','file'),(null as any));
    this._NgFileSelectDirective_49_3 = new import18.Wrapper_NgFileSelectDirective(new import21.ElementRef(this._el_49));
    this._text_50 = this.renderer.createText(this._el_33,'\n								',(null as any));
    this._el_51 = import4.createRenderElement(this.renderer,this._el_33,'div',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_52 = this.renderer.createText(this._el_51,'',(null as any));
    this._text_53 = this.renderer.createText(this._el_33,'\n\n								',(null as any));
    this._el_54 = import4.createRenderElement(this.renderer,this._el_33,'div',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_55 = this.renderer.createText(this._el_54,'',(null as any));
    this._text_56 = this.renderer.createText(this._el_33,'\n\n						',(null as any));
    this._text_57 = this.renderer.createText(this._el_13,'\n					',(null as any));
    this._text_58 = this.renderer.createText(this._el_8,'\n					',(null as any));
    this._el_59 = import4.createRenderElement(this.renderer,this._el_8,'br',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_60 = this.renderer.createText(this._el_8,'\n					',(null as any));
    this._el_61 = import4.createRenderElement(this.renderer,this._el_8,'div',new import4.InlineArray2(2,'class','row'),(null as any));
    this._text_62 = this.renderer.createText(this._el_61,'\n						',(null as any));
    this._el_63 = import4.createRenderElement(this.renderer,this._el_61,'div',new import4.InlineArray2(2,'class','col-md-12'),(null as any));
    this._text_64 = this.renderer.createText(this._el_63,'\n							',(null as any));
    this._el_65 = import4.createRenderElement(this.renderer,this._el_63,'h3',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_66 = this.renderer.createText(this._el_65,'Search Pending:',(null as any));
    this._text_67 = this.renderer.createText(this._el_63,'\n							',(null as any));
    this._el_68 = import4.createRenderElement(this.renderer,this._el_63,'div',new import4.InlineArray2(2,'class','table-responsive'),(null as any));
    this._text_69 = this.renderer.createText(this._el_68,'\n								\n								',(null as any));
    this._el_70 = import4.createRenderElement(this.renderer,this._el_68,'table',new import4.InlineArray2(2,'class','table table-bordered'),(null as any));
    this._text_71 = this.renderer.createText(this._el_70,'\n									',(null as any));
    this._el_72 = import4.createRenderElement(this.renderer,this._el_70,'thead',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_73 = this.renderer.createText(this._el_72,'\n										',(null as any));
    this._el_74 = import4.createRenderElement(this.renderer,this._el_72,'tr',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_75 = this.renderer.createText(this._el_74,'\n											',(null as any));
    this._el_76 = import4.createRenderElement(this.renderer,this._el_74,'th',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_77 = this.renderer.createText(this._el_76,'Name to search',(null as any));
    this._text_78 = this.renderer.createText(this._el_74,'\n											',(null as any));
    this._el_79 = import4.createRenderElement(this.renderer,this._el_74,'th',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_80 = this.renderer.createText(this._el_79,'SearchDate',(null as any));
    this._text_81 = this.renderer.createText(this._el_74,'\n											',(null as any));
    this._el_82 = import4.createRenderElement(this.renderer,this._el_74,'th',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_83 = this.renderer.createText(this._el_82,'MatchSummary',(null as any));
    this._text_84 = this.renderer.createText(this._el_74,'\n											',(null as any));
    this._el_85 = import4.createRenderElement(this.renderer,this._el_74,'th',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_86 = this.renderer.createText(this._el_85,'ProcessedSummary',(null as any));
    this._text_87 = this.renderer.createText(this._el_74,'\n										',(null as any));
    this._text_88 = this.renderer.createText(this._el_72,'\n									',(null as any));
    this._text_89 = this.renderer.createText(this._el_70,'\n									',(null as any));
    this._el_90 = import4.createRenderElement(this.renderer,this._el_70,'tbody',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_91 = this.renderer.createText(this._el_90,'\n										',(null as any));
    this._anchor_92 = this.renderer.createTemplateAnchor(this._el_90,(null as any));
    this._appEl_92 = new import3.AppElement(92,90,this,this._anchor_92);
    this._TemplateRef_92_5 = new import22.TemplateRef_(this._appEl_92,viewFactory_SearchInputComponent1);
    this._NgFor_92_6 = new import19.Wrapper_NgFor(this._appEl_92.vcRef,this._TemplateRef_92_5,this.parentInjector.get(import23.IterableDiffers),this.ref);
    this._text_93 = this.renderer.createText(this._el_90,'\n\n									',(null as any));
    this._text_94 = this.renderer.createText(this._el_70,'\n								',(null as any));
    this._text_95 = this.renderer.createText(this._el_68,'\n							',(null as any));
    this._text_96 = this.renderer.createText(this._el_63,'\n\n\n\n							',(null as any));
    this._el_97 = import4.createRenderElement(this.renderer,this._el_63,'div',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_98 = this.renderer.createText(this._el_97,'\n\n\n							',(null as any));
    this._text_99 = this.renderer.createText(this._el_63,'\n						',(null as any));
    this._text_100 = this.renderer.createText(this._el_61,'\n					',(null as any));
    this._text_101 = this.renderer.createText(this._el_8,'\n				',(null as any));
    this._text_102 = this.renderer.createText(this._el_6,'\n\n			',(null as any));
    this._text_103 = this.renderer.createText(this._el_4,'\n		',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_17,'submit',this.eventHandler(this._handle_submit_17_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_17,'reset',this.eventHandler(this._handle_reset_17_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_25,'ngModelChange',this.eventHandler(this._handle_ngModelChange_25_0.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_25,'input',this.eventHandler(this._handle_input_25_1.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_25,'blur',this.eventHandler(this._handle_blur_25_2.bind(this)));
    const subscription_0:any = this._NgModel_25_7.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_25_0.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_28,'click',this.eventHandler(this._handle_click_28_0.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_35,'submit',this.eventHandler(this._handle_submit_35_0.bind(this)));
    var disposable_7:Function = this.renderer.listen(this._el_35,'reset',this.eventHandler(this._handle_reset_35_1.bind(this)));
    var disposable_8:Function = this.renderer.listen(this._el_49,'onUpload',this.eventHandler(this._handle_onUpload_49_0.bind(this)));
    var disposable_9:Function = this.renderer.listen(this._el_49,'change',this.eventHandler(this._handle_change_49_1.bind(this)));
    const subscription_1:any = this._NgFileSelectDirective_49_3.context.onUpload.subscribe(this.eventHandler(this._handle_onUpload_49_0.bind(this)));
    this._pipe_json_0 = new import20.JsonPipe();
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._text_56,
      this._text_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._el_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._el_76,
      this._text_77,
      this._text_78,
      this._el_79,
      this._text_80,
      this._text_81,
      this._el_82,
      this._text_83,
      this._text_84,
      this._el_85,
      this._text_86,
      this._text_87,
      this._text_88,
      this._text_89,
      this._el_90,
      this._text_91,
      this._anchor_92,
      this._text_93,
      this._text_94,
      this._text_95,
      this._text_96,
      this._el_97,
      this._text_98,
      this._text_99,
      this._text_100,
      this._text_101,
      this._text_102,
      this._text_103
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8,
      disposable_9
    ]
    ,[
      subscription_0,
      subscription_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import24.DefaultValueAccessor) && (25 === requestNodeIndex))) { return this._DefaultValueAccessor_25_3.context; }
    if (((token === import25.RequiredValidator) && (25 === requestNodeIndex))) { return this._RequiredValidator_25_4.context; }
    if (((token === import26.NG_VALIDATORS) && (25 === requestNodeIndex))) { return this._NG_VALIDATORS_25_5; }
    if (((token === import27.NG_VALUE_ACCESSOR) && (25 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_25_6; }
    if (((token === import28.NgModel) && (25 === requestNodeIndex))) { return this._NgModel_25_7.context; }
    if (((token === import29.NgControl) && (25 === requestNodeIndex))) { return this._NgControl_25_8; }
    if (((token === import30.NgControlStatus) && (25 === requestNodeIndex))) { return this._NgControlStatus_25_9.context; }
    if (((token === import31.NgForm) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._NgForm_17_3.context; }
    if (((token === import32.ControlContainer) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._ControlContainer_17_4; }
    if (((token === import30.NgControlStatusGroup) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._NgControlStatusGroup_17_5.context; }
    if (((token === import31.NgForm) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._NgForm_35_3.context; }
    if (((token === import32.ControlContainer) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._ControlContainer_35_4; }
    if (((token === import30.NgControlStatusGroup) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._NgControlStatusGroup_35_5.context; }
    if (((token === import33.NgFileSelectDirective) && (49 === requestNodeIndex))) { return this._NgFileSelectDirective_49_3.context; }
    if (((token === import22.TemplateRef) && (92 === requestNodeIndex))) { return this._TemplateRef_92_5; }
    if (((token === import34.NgFor) && (92 === requestNodeIndex))) { return this._NgFor_92_6.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    this._NgForm_17_3.detectChangesInInputProps(this,this._el_17,throwOnChange);
    this._NgControlStatusGroup_17_5.detectChangesInInputProps(this,this._el_17,throwOnChange);
    this._DefaultValueAccessor_25_3.detectChangesInInputProps(this,this._el_25,throwOnChange);
    const currVal_25_1_0:any = '';
    this._RequiredValidator_25_4.check_required(currVal_25_1_0,throwOnChange,false);
    this._RequiredValidator_25_4.detectChangesInInputProps(this,this._el_25,throwOnChange);
    const currVal_25_2_0:any = 'NameToSearch';
    this._NgModel_25_7.check_name(currVal_25_2_0,throwOnChange,false);
    const currVal_25_2_1:any = this.context.NameToSearch;
    this._NgModel_25_7.check_model(currVal_25_2_1,throwOnChange,false);
    this._NgModel_25_7.detectChangesInInputProps(this,this._el_25,throwOnChange);
    this._NgControlStatus_25_9.detectChangesInInputProps(this,this._el_25,throwOnChange);
    this._NgForm_35_3.detectChangesInInputProps(this,this._el_35,throwOnChange);
    this._NgControlStatusGroup_35_5.detectChangesInInputProps(this,this._el_35,throwOnChange);
    const currVal_49_0_0:any = this.context.basicOptions;
    this._NgFileSelectDirective_49_3.check_options(currVal_49_0_0,throwOnChange,false);
    this._NgFileSelectDirective_49_3.detectChangesInInputProps(this,this._el_49,throwOnChange);
    const currVal_92_0_0:any = this.context.ComplianceFormSummaryList;
    this._NgFor_92_6.check_ngForOf(currVal_92_0_0,throwOnChange,false);
    this._NgFor_92_6.detectChangesInInputProps(this,this._anchor_92,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._NgForm_17_3.detectChangesInHostProps(this,this._el_17,throwOnChange);
    this._NgControlStatusGroup_17_5.detectChangesInHostProps(this,this._el_17,throwOnChange);
    this._DefaultValueAccessor_25_3.detectChangesInHostProps(this,this._el_25,throwOnChange);
    this._RequiredValidator_25_4.detectChangesInHostProps(this,this._el_25,throwOnChange);
    this._NgModel_25_7.detectChangesInHostProps(this,this._el_25,throwOnChange);
    this._NgControlStatus_25_9.detectChangesInHostProps(this,this._el_25,throwOnChange);
    const currVal_121:boolean = !this._NgForm_17_3.context.form.valid;
    if (import4.checkBinding(throwOnChange,this._expr_121,currVal_121)) {
      this.renderer.setElementProperty(this._el_28,'disabled',currVal_121);
      this._expr_121 = currVal_121;
    }
    const currVal_122:any = import4.interpolate(1,'',this.context.uploadUrl,'');
    if (import4.checkBinding(throwOnChange,this._expr_122,currVal_122)) {
      this.renderer.setElementProperty(this._el_35,'action',this.viewUtils.sanitizer.sanitize(import35.SecurityContext.URL,currVal_122));
      this._expr_122 = currVal_122;
    }
    this._NgForm_35_3.detectChangesInHostProps(this,this._el_35,throwOnChange);
    this._NgControlStatusGroup_35_5.detectChangesInHostProps(this,this._el_35,throwOnChange);
    this._NgFileSelectDirective_49_3.detectChangesInHostProps(this,this._el_49,throwOnChange);
    valUnwrapper.reset();
    const currVal_123:any = import4.interpolate(1,'\n									Response: ',valUnwrapper.unwrap(this._pipe_json_0.transform(this.context.response)),'\n								');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_123,currVal_123))) {
      this.renderer.setText(this._text_52,currVal_123);
      this._expr_123 = currVal_123;
    }
    const currVal_125:any = import4.interpolate(1,'\n									Progress: ',this.context.progress,'%\n								');
    if (import4.checkBinding(throwOnChange,this._expr_125,currVal_125)) {
      this.renderer.setText(this._text_55,currVal_125);
      this._expr_125 = currVal_125;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_25_7.context.ngOnDestroy();
  }
  private _handle_submit_17_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_17_0:any = ((<any>this._NgForm_17_3.context.onSubmit($event)) !== false);
    return (true && pd_17_0);
  }
  private _handle_reset_17_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_17_0:any = ((<any>this._NgForm_17_3.context.onReset()) !== false);
    return (true && pd_17_0);
  }
  private _handle_ngModelChange_25_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_25_0:any = ((<any>(this.context.NameToSearch = $event)) !== false);
    const pd_25_1:any = ((<any>(this.context.NameToSearch = $event)) !== false);
    return ((true && pd_25_0) && pd_25_1);
  }
  private _handle_input_25_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_25_0:any = ((<any>this._DefaultValueAccessor_25_3.context.onChange($event.target.value)) !== false);
    return (true && pd_25_0);
  }
  private _handle_blur_25_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_25_0:any = ((<any>this._DefaultValueAccessor_25_3.context.onTouched()) !== false);
    return (true && pd_25_0);
  }
  private _handle_click_28_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_28_0:any = ((<any>this.context.goToSearch()) !== false);
    return (true && pd_28_0);
  }
  private _handle_submit_35_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_35_0:any = ((<any>this._NgForm_35_3.context.onSubmit($event)) !== false);
    return (true && pd_35_0);
  }
  private _handle_reset_35_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_35_0:any = ((<any>this._NgForm_35_3.context.onReset()) !== false);
    return (true && pd_35_0);
  }
  private _handle_onUpload_49_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_49_0:any = ((<any>this.context.handleUpload($event)) !== false);
    return (true && pd_49_0);
  }
  private _handle_change_49_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_49_0:any = ((<any>this._NgFileSelectDirective_49_3.context.onChange()) !== false);
    return (true && pd_49_0);
  }
}
export function viewFactory_SearchInputComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.SearchInputComponent> {
  if ((renderType_SearchInputComponent === (null as any))) { (renderType_SearchInputComponent = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,styles_SearchInputComponent,{})); }
  return new _View_SearchInputComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_SearchInputComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_SearchInputComponent1,renderType_SearchInputComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.createRenderElement(this.renderer,(null as any),'tr',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n\n											',(null as any));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'td',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n											',(null as any));
    this._el_5 = import4.createRenderElement(this.renderer,this._el_0,'td',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n											',(null as any));
    this._el_8 = import4.createRenderElement(this.renderer,this._el_0,'td',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_9 = this.renderer.createText(this._el_8,'',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n											',(null as any));
    this._el_11 = import4.createRenderElement(this.renderer,this._el_0,'td',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_12 = this.renderer.createText(this._el_11,'',(null as any));
    this._text_13 = this.renderer.createText(this._el_0,'\n										',(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_14:any = import4.interpolate(1,'\n												',this.context.$implicit.NameToSearch,'\n											');
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setText(this._text_3,currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = import4.interpolate(1,'\n												',this.context.$implicit.SearchDate,'\n											');
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setText(this._text_6,currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = import4.interpolate(1,'\n												',this.context.$implicit.MatchSummary,'\n											');
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setText(this._text_9,currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = import4.interpolate(1,'\n												',this.context.$implicit.ProcessedSummary,'\n											');
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setText(this._text_12,currVal_17);
      this._expr_17 = currVal_17;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SearchInputComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_SearchInputComponent1(viewUtils,parentInjector,declarationEl);
}