/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['table[_ngcontent-%COMP%] {\r\n    border-collapse: collapse;\r\n    width: 100%;\r\n}\r\n\r\nth[_ngcontent-%COMP%], td[_ngcontent-%COMP%] {\r\n    padding: 8px;\r\n    text-align: left;\r\n    border-bottom: 1px solid #ddd;\r\n}\r\nth[_ngcontent-%COMP%]{background-color:#AED6F1  }\r\n\r\ntr[_ngcontent-%COMP%]:hover{background-color:#E8DAEF;  }\r\n\r\n\r\ntr[_ngcontent-%COMP%]:nth-child(odd){\r\n     background-color:#EAECEE;\r\n}\r\n\r\n tr[_ngcontent-%COMP%]:nth-child(odd):hover{\r\n     background-color:#E8DAEF;\r\n}'];