/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '../../../app/auth/login.component';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../../app/auth/auth.service';
import * as import9 from '@angular/router/src/router';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from '../../node_modules/@angular/forms/src/directives/ng_form.ngfactory';
import * as import13 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import14 from '../../node_modules/@angular/forms/src/directives/default_value_accessor.ngfactory';
import * as import15 from '../../node_modules/@angular/forms/src/directives/validators.ngfactory';
import * as import16 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import17 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import18 from '@angular/core/src/linker/element_ref';
import * as import19 from '@angular/core/src/linker/template_ref';
import * as import20 from '@angular/forms/src/directives/default_value_accessor';
import * as import21 from '@angular/forms/src/directives/validators';
import * as import22 from '@angular/forms/src/validators';
import * as import23 from '@angular/forms/src/directives/control_value_accessor';
import * as import24 from '@angular/forms/src/directives/ng_model';
import * as import25 from '@angular/forms/src/directives/ng_control';
import * as import26 from '@angular/forms/src/directives/ng_control_status';
import * as import27 from '@angular/common/src/directives/ng_if';
import * as import28 from '@angular/forms/src/directives/ng_form';
import * as import29 from '@angular/forms/src/directives/control_container';
export class Wrapper_LoginComponent {
  context:import0.LoginComponent;
  changed:boolean;
  constructor(p0:any,p1:any) {
    this.changed = false;
    this.context = new import0.LoginComponent(p0,p1);
  }
  detectChangesInInputProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
  detectChangesInHostProps(view:import1.AppView<any>,el:any,throwOnChange:boolean):void {
  }
}
var renderType_LoginComponent_Host:import2.RenderComponentType = (null as any);
class _View_LoginComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _LoginComponent_0_4:Wrapper_LoginComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_LoginComponent_Host0,renderType_LoginComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.selectOrCreateRenderHostElement(this.renderer,'ng-component',import4.EMPTY_INLINE_ARRAY,rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_LoginComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._LoginComponent_0_4 = new Wrapper_LoginComponent(this.parentInjector.get(import8.AuthService),this.parentInjector.get(import9.Router));
    this._appEl_0.initComponent(this._LoginComponent_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._LoginComponent_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.LoginComponent) && (0 === requestNodeIndex))) { return this._LoginComponent_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._LoginComponent_0_4.detectChangesInInputProps(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._LoginComponent_0_4.detectChangesInHostProps(this,this._el_0,throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_LoginComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_LoginComponent_Host === (null as any))) { (renderType_LoginComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_LoginComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const LoginComponentNgFactory:import11.ComponentFactory<import0.LoginComponent> = new import11.ComponentFactory<import0.LoginComponent>('ng-component',viewFactory_LoginComponent_Host0,import0.LoginComponent);
const styles_LoginComponent:any[] = ([] as any[]);
var renderType_LoginComponent:import2.RenderComponentType = (null as any);
class _View_LoginComponent0 extends import1.AppView<import0.LoginComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _NgForm_5_3:import12.Wrapper_NgForm;
  _ControlContainer_5_4:any;
  _NgControlStatusGroup_5_5:import13.Wrapper_NgControlStatusGroup;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _DefaultValueAccessor_13_3:import14.Wrapper_DefaultValueAccessor;
  _RequiredValidator_13_4:import15.Wrapper_RequiredValidator;
  _NG_VALIDATORS_13_5:any[];
  _NG_VALUE_ACCESSOR_13_6:any[];
  _NgModel_13_7:import16.Wrapper_NgModel;
  _NgControl_13_8:any;
  _NgControlStatus_13_9:import13.Wrapper_NgControlStatus;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _DefaultValueAccessor_22_3:import14.Wrapper_DefaultValueAccessor;
  _RequiredValidator_22_4:import15.Wrapper_RequiredValidator;
  _NG_VALIDATORS_22_5:any[];
  _NG_VALUE_ACCESSOR_22_6:any[];
  _NgModel_22_7:import16.Wrapper_NgModel;
  _NgControl_22_8:any;
  _NgControlStatus_22_9:import13.Wrapper_NgControlStatus;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _text_29:any;
  _anchor_30:any;
  /*private*/ _appEl_30:import3.AppElement;
  _TemplateRef_30_5:any;
  _NgIf_30_6:import17.Wrapper_NgIf;
  _text_31:any;
  _text_32:any;
  _anchor_33:any;
  /*private*/ _appEl_33:import3.AppElement;
  _TemplateRef_33_5:any;
  _NgIf_33_6:import17.Wrapper_NgIf;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  /*private*/ _expr_60:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_LoginComponent0,renderType_LoginComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_60 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = import4.createRenderElement(this.renderer,parentRenderNode,'div',new import4.InlineArray2(2,'class','col-md-6 col-md-offset-3'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n    \n    ',(null as any));
    this._el_2 = import4.createRenderElement(this.renderer,this._el_0,'h2',import4.EMPTY_INLINE_ARRAY,(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'Login',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_5 = import4.createRenderElement(this.renderer,this._el_0,'form',new import4.InlineArray4(4,'name','form','novalidate',''),(null as any));
    this._NgForm_5_3 = new import12.Wrapper_NgForm((null as any),(null as any));
    this._ControlContainer_5_4 = this._NgForm_5_3.context;
    this._NgControlStatusGroup_5_5 = new import13.Wrapper_NgControlStatusGroup(this._ControlContainer_5_4);
    this._text_6 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._el_7 = import4.createRenderElement(this.renderer,this._el_5,'div',new import4.InlineArray2(2,'class','form-group'),(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._el_9 = import4.createRenderElement(this.renderer,this._el_7,'label',new import4.InlineArray2(2,'for','username'),(null as any));
    this._text_10 = this.renderer.createText(this._el_9,'Username',(null as any));
    this._text_11 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._text_12 = this.renderer.createText(this._el_7,'\n            ',(null as any));
    this._el_13 = import4.createRenderElement(this.renderer,this._el_7,'input',new import4.InlineArray8(8,'class','form-control','name','username','required','','type','text'),(null as any));
    this._DefaultValueAccessor_13_3 = new import14.Wrapper_DefaultValueAccessor(this.renderer,new import18.ElementRef(this._el_13));
    this._RequiredValidator_13_4 = new import15.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_13_5 = [this._RequiredValidator_13_4.context];
    this._NG_VALUE_ACCESSOR_13_6 = [this._DefaultValueAccessor_13_3.context];
    this._NgModel_13_7 = new import16.Wrapper_NgModel(this._ControlContainer_5_4,this._NG_VALIDATORS_13_5,(null as any),this._NG_VALUE_ACCESSOR_13_6);
    this._NgControl_13_8 = this._NgModel_13_7.context;
    this._NgControlStatus_13_9 = new import13.Wrapper_NgControlStatus(this._NgControl_13_8);
    this._text_14 = this.renderer.createText(this._el_7,'\n            \n        ',(null as any));
    this._text_15 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._el_16 = import4.createRenderElement(this.renderer,this._el_5,'div',new import4.InlineArray2(2,'class','form-group'),(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'\n            ',(null as any));
    this._el_18 = import4.createRenderElement(this.renderer,this._el_16,'label',new import4.InlineArray2(2,'for','password'),(null as any));
    this._text_19 = this.renderer.createText(this._el_18,'Password',(null as any));
    this._text_20 = this.renderer.createText(this._el_16,'\n            ',(null as any));
    this._text_21 = this.renderer.createText(this._el_16,'\n            ',(null as any));
    this._el_22 = import4.createRenderElement(this.renderer,this._el_16,'input',new import4.InlineArray8(8,'class','form-control','name','password','required','','type','password'),(null as any));
    this._DefaultValueAccessor_22_3 = new import14.Wrapper_DefaultValueAccessor(this.renderer,new import18.ElementRef(this._el_22));
    this._RequiredValidator_22_4 = new import15.Wrapper_RequiredValidator();
    this._NG_VALIDATORS_22_5 = [this._RequiredValidator_22_4.context];
    this._NG_VALUE_ACCESSOR_22_6 = [this._DefaultValueAccessor_22_3.context];
    this._NgModel_22_7 = new import16.Wrapper_NgModel(this._ControlContainer_5_4,this._NG_VALIDATORS_22_5,(null as any),this._NG_VALUE_ACCESSOR_22_6);
    this._NgControl_22_8 = this._NgModel_22_7.context;
    this._NgControlStatus_22_9 = new import13.Wrapper_NgControlStatus(this._NgControl_22_8);
    this._text_23 = this.renderer.createText(this._el_16,'\n            \n        ',(null as any));
    this._text_24 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._el_25 = import4.createRenderElement(this.renderer,this._el_5,'div',new import4.InlineArray2(2,'class','form-group'),(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'\n            ',(null as any));
    this._el_27 = import4.createRenderElement(this.renderer,this._el_25,'button',new import4.InlineArray2(2,'class','btn btn-primary'),(null as any));
    this._text_28 = this.renderer.createText(this._el_27,'Login',(null as any));
    this._text_29 = this.renderer.createText(this._el_25,'\n            ',(null as any));
    this._anchor_30 = this.renderer.createTemplateAnchor(this._el_25,(null as any));
    this._appEl_30 = new import3.AppElement(30,25,this,this._anchor_30);
    this._TemplateRef_30_5 = new import19.TemplateRef_(this._appEl_30,viewFactory_LoginComponent1);
    this._NgIf_30_6 = new import17.Wrapper_NgIf(this._appEl_30.vcRef,this._TemplateRef_30_5);
    this._text_31 = this.renderer.createText(this._el_25,'\n        ',(null as any));
    this._text_32 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._anchor_33 = this.renderer.createTemplateAnchor(this._el_5,(null as any));
    this._appEl_33 = new import3.AppElement(33,5,this,this._anchor_33);
    this._TemplateRef_33_5 = new import19.TemplateRef_(this._appEl_33,viewFactory_LoginComponent2);
    this._NgIf_33_6 = new import17.Wrapper_NgIf(this._appEl_33.vcRef,this._TemplateRef_33_5);
    this._text_34 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._text_35 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_36 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_5,'submit',this.eventHandler(this._handle_submit_5_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_5,'reset',this.eventHandler(this._handle_reset_5_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_13,'ngModelChange',this.eventHandler(this._handle_ngModelChange_13_0.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_13,'input',this.eventHandler(this._handle_input_13_1.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_13,'blur',this.eventHandler(this._handle_blur_13_2.bind(this)));
    const subscription_0:any = this._NgModel_13_7.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_13_0.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_22,'ngModelChange',this.eventHandler(this._handle_ngModelChange_22_0.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_22,'input',this.eventHandler(this._handle_input_22_1.bind(this)));
    var disposable_7:Function = this.renderer.listen(this._el_22,'blur',this.eventHandler(this._handle_blur_22_2.bind(this)));
    const subscription_1:any = this._NgModel_22_7.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_22_0.bind(this)));
    var disposable_8:Function = this.renderer.listen(this._el_27,'click',this.eventHandler(this._handle_click_27_0.bind(this)));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._text_29,
      this._anchor_30,
      this._text_31,
      this._text_32,
      this._anchor_33,
      this._text_34,
      this._text_35,
      this._text_36
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7,
      disposable_8
    ]
    ,[
      subscription_0,
      subscription_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.DefaultValueAccessor) && (13 === requestNodeIndex))) { return this._DefaultValueAccessor_13_3.context; }
    if (((token === import21.RequiredValidator) && (13 === requestNodeIndex))) { return this._RequiredValidator_13_4.context; }
    if (((token === import22.NG_VALIDATORS) && (13 === requestNodeIndex))) { return this._NG_VALIDATORS_13_5; }
    if (((token === import23.NG_VALUE_ACCESSOR) && (13 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_13_6; }
    if (((token === import24.NgModel) && (13 === requestNodeIndex))) { return this._NgModel_13_7.context; }
    if (((token === import25.NgControl) && (13 === requestNodeIndex))) { return this._NgControl_13_8; }
    if (((token === import26.NgControlStatus) && (13 === requestNodeIndex))) { return this._NgControlStatus_13_9.context; }
    if (((token === import20.DefaultValueAccessor) && (22 === requestNodeIndex))) { return this._DefaultValueAccessor_22_3.context; }
    if (((token === import21.RequiredValidator) && (22 === requestNodeIndex))) { return this._RequiredValidator_22_4.context; }
    if (((token === import22.NG_VALIDATORS) && (22 === requestNodeIndex))) { return this._NG_VALIDATORS_22_5; }
    if (((token === import23.NG_VALUE_ACCESSOR) && (22 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_22_6; }
    if (((token === import24.NgModel) && (22 === requestNodeIndex))) { return this._NgModel_22_7.context; }
    if (((token === import25.NgControl) && (22 === requestNodeIndex))) { return this._NgControl_22_8; }
    if (((token === import26.NgControlStatus) && (22 === requestNodeIndex))) { return this._NgControlStatus_22_9.context; }
    if (((token === import19.TemplateRef) && (30 === requestNodeIndex))) { return this._TemplateRef_30_5; }
    if (((token === import27.NgIf) && (30 === requestNodeIndex))) { return this._NgIf_30_6.context; }
    if (((token === import19.TemplateRef) && (33 === requestNodeIndex))) { return this._TemplateRef_33_5; }
    if (((token === import27.NgIf) && (33 === requestNodeIndex))) { return this._NgIf_33_6.context; }
    if (((token === import28.NgForm) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._NgForm_5_3.context; }
    if (((token === import29.ControlContainer) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._ControlContainer_5_4; }
    if (((token === import26.NgControlStatusGroup) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._NgControlStatusGroup_5_5.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._NgForm_5_3.detectChangesInInputProps(this,this._el_5,throwOnChange);
    this._NgControlStatusGroup_5_5.detectChangesInInputProps(this,this._el_5,throwOnChange);
    this._DefaultValueAccessor_13_3.detectChangesInInputProps(this,this._el_13,throwOnChange);
    const currVal_13_1_0:any = '';
    this._RequiredValidator_13_4.check_required(currVal_13_1_0,throwOnChange,false);
    this._RequiredValidator_13_4.detectChangesInInputProps(this,this._el_13,throwOnChange);
    const currVal_13_2_0:any = 'username';
    this._NgModel_13_7.check_name(currVal_13_2_0,throwOnChange,false);
    const currVal_13_2_1:any = this.context.logInfo.username;
    this._NgModel_13_7.check_model(currVal_13_2_1,throwOnChange,false);
    this._NgModel_13_7.detectChangesInInputProps(this,this._el_13,throwOnChange);
    this._NgControlStatus_13_9.detectChangesInInputProps(this,this._el_13,throwOnChange);
    this._DefaultValueAccessor_22_3.detectChangesInInputProps(this,this._el_22,throwOnChange);
    const currVal_22_1_0:any = '';
    this._RequiredValidator_22_4.check_required(currVal_22_1_0,throwOnChange,false);
    this._RequiredValidator_22_4.detectChangesInInputProps(this,this._el_22,throwOnChange);
    const currVal_22_2_0:any = 'password';
    this._NgModel_22_7.check_name(currVal_22_2_0,throwOnChange,false);
    const currVal_22_2_1:any = this.context.logInfo.password;
    this._NgModel_22_7.check_model(currVal_22_2_1,throwOnChange,false);
    this._NgModel_22_7.detectChangesInInputProps(this,this._el_22,throwOnChange);
    this._NgControlStatus_22_9.detectChangesInInputProps(this,this._el_22,throwOnChange);
    const currVal_30_0_0:any = this.context.loading;
    this._NgIf_30_6.check_ngIf(currVal_30_0_0,throwOnChange,false);
    this._NgIf_30_6.detectChangesInInputProps(this,this._anchor_30,throwOnChange);
    const currVal_33_0_0:any = this.context.error;
    this._NgIf_33_6.check_ngIf(currVal_33_0_0,throwOnChange,false);
    this._NgIf_33_6.detectChangesInInputProps(this,this._anchor_33,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this._NgForm_5_3.detectChangesInHostProps(this,this._el_5,throwOnChange);
    this._NgControlStatusGroup_5_5.detectChangesInHostProps(this,this._el_5,throwOnChange);
    this._DefaultValueAccessor_13_3.detectChangesInHostProps(this,this._el_13,throwOnChange);
    this._RequiredValidator_13_4.detectChangesInHostProps(this,this._el_13,throwOnChange);
    this._NgModel_13_7.detectChangesInHostProps(this,this._el_13,throwOnChange);
    this._NgControlStatus_13_9.detectChangesInHostProps(this,this._el_13,throwOnChange);
    this._DefaultValueAccessor_22_3.detectChangesInHostProps(this,this._el_22,throwOnChange);
    this._RequiredValidator_22_4.detectChangesInHostProps(this,this._el_22,throwOnChange);
    this._NgModel_22_7.detectChangesInHostProps(this,this._el_22,throwOnChange);
    this._NgControlStatus_22_9.detectChangesInHostProps(this,this._el_22,throwOnChange);
    const currVal_60:any = this.context.loading;
    if (import4.checkBinding(throwOnChange,this._expr_60,currVal_60)) {
      this.renderer.setElementProperty(this._el_27,'disabled',currVal_60);
      this._expr_60 = currVal_60;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_13_7.context.ngOnDestroy();
    this._NgModel_22_7.context.ngOnDestroy();
  }
  private _handle_submit_5_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_5_0:any = ((<any>this._NgForm_5_3.context.onSubmit($event)) !== false);
    return (true && pd_5_0);
  }
  private _handle_reset_5_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_5_0:any = ((<any>this._NgForm_5_3.context.onReset()) !== false);
    return (true && pd_5_0);
  }
  private _handle_ngModelChange_13_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_13_0:any = ((<any>(this.context.logInfo.username = $event)) !== false);
    return (true && pd_13_0);
  }
  private _handle_input_13_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_13_0:any = ((<any>this._DefaultValueAccessor_13_3.context.onChange($event.target.value)) !== false);
    return (true && pd_13_0);
  }
  private _handle_blur_13_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_13_0:any = ((<any>this._DefaultValueAccessor_13_3.context.onTouched()) !== false);
    return (true && pd_13_0);
  }
  private _handle_ngModelChange_22_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_22_0:any = ((<any>(this.context.logInfo.password = $event)) !== false);
    return (true && pd_22_0);
  }
  private _handle_input_22_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_22_0:any = ((<any>this._DefaultValueAccessor_22_3.context.onChange($event.target.value)) !== false);
    return (true && pd_22_0);
  }
  private _handle_blur_22_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_22_0:any = ((<any>this._DefaultValueAccessor_22_3.context.onTouched()) !== false);
    return (true && pd_22_0);
  }
  private _handle_click_27_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_27_0:any = ((<any>this.context.login()) !== false);
    return (true && pd_27_0);
  }
}
export function viewFactory_LoginComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.LoginComponent> {
  if ((renderType_LoginComponent === (null as any))) { (renderType_LoginComponent = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,styles_LoginComponent,{})); }
  return new _View_LoginComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_LoginComponent1 extends import1.AppView<any> {
  _el_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_LoginComponent1,renderType_LoginComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.createRenderElement(this.renderer,(null as any),'img',new import4.InlineArray2(2,'src','data:image/gif;base64,R0lGODlhEAAQAPIAAP///wAAAMLCwkJCQgAAAGJiYoKCgpKSkiH/C05FVFNDQVBFMi4wAwEAAAAh/hpDcmVhdGVkIHdpdGggYWpheGxvYWQuaW5mbwAh+QQJCgAAACwAAAAAEAAQAAADMwi63P4wyklrE2MIOggZnAdOmGYJRbExwroUmcG2LmDEwnHQLVsYOd2mBzkYDAdKa+dIAAAh+QQJCgAAACwAAAAAEAAQAAADNAi63P5OjCEgG4QMu7DmikRxQlFUYDEZIGBMRVsaqHwctXXf7WEYB4Ag1xjihkMZsiUkKhIAIfkECQoAAAAsAAAAABAAEAAAAzYIujIjK8pByJDMlFYvBoVjHA70GU7xSUJhmKtwHPAKzLO9HMaoKwJZ7Rf8AYPDDzKpZBqfvwQAIfkECQoAAAAsAAAAABAAEAAAAzMIumIlK8oyhpHsnFZfhYumCYUhDAQxRIdhHBGqRoKw0R8DYlJd8z0fMDgsGo/IpHI5TAAAIfkECQoAAAAsAAAAABAAEAAAAzIIunInK0rnZBTwGPNMgQwmdsNgXGJUlIWEuR5oWUIpz8pAEAMe6TwfwyYsGo/IpFKSAAAh+QQJCgAAACwAAAAAEAAQAAADMwi6IMKQORfjdOe82p4wGccc4CEuQradylesojEMBgsUc2G7sDX3lQGBMLAJibufbSlKAAAh+QQJCgAAACwAAAAAEAAQAAADMgi63P7wCRHZnFVdmgHu2nFwlWCI3WGc3TSWhUFGxTAUkGCbtgENBMJAEJsxgMLWzpEAACH5BAkKAAAALAAAAAAQABAAAAMyCLrc/jDKSatlQtScKdceCAjDII7HcQ4EMTCpyrCuUBjCYRgHVtqlAiB1YhiCnlsRkAAAOwAAAAAAAAAAAA=='),(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return (null as any);
  }
}
function viewFactory_LoginComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_LoginComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_LoginComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_LoginComponent2,renderType_LoginComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
    this._expr_2 = import7.UNINITIALIZED;
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = import4.createRenderElement(this.renderer,(null as any),'div',new import4.InlineArray2(2,'class','alert alert-danger'),(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_2:any = import4.interpolate(1,'',this.parent.context.error,'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_1,currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_LoginComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_LoginComponent2(viewUtils,parentInjector,declarationEl);
}